# Documentation: https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "nuget" # https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#package-ecosystem-
    directories:
      - "/src/Tests/Toolkit.Tests"
      - "/src/Tests/UITests/*"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    cooldown:
      default-days: 2
    schedule:
      interval: "weekly"
