#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Esri.ArcGISRuntime.Toolkit.SampleApp.Resource", IsApplication=true)]

namespace Esri.ArcGISRuntime.Toolkit.SampleApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.barrierAllowsGoneWidgets = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.barrierAllowsGoneWidgets;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.barrierDirection = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.barrierDirection;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.chainUseRtl = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.chainUseRtl;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.constraintSet = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.constraintSet;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.constraint_referenced_ids = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.constraint_referenced_ids;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.content = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.content;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.emptyVisibility = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.emptyVisibility;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_constrainedHeight = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_constrainedHeight;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_constrainedWidth = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_constrainedWidth;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_constraintBaseline_creator = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_constraintBaseline_creator;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_constraintBaseline_toBaselineOf = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_constraintBaseline_toBaselineOf;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_constraintBottom_creator = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_constraintBottom_creator;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_constraintBottom_toBottomOf = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_constraintBottom_toBottomOf;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_constraintBottom_toTopOf = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_constraintBottom_toTopOf;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_constraintCircle = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_constraintCircle;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_constraintCircleAngle = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_constraintCircleAngle;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_constraintCircleRadius = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_constraintCircleRadius;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_constraintDimensionRatio = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_constraintDimensionRatio;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_constraintEnd_toEndOf = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_constraintEnd_toEndOf;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_constraintEnd_toStartOf = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_constraintEnd_toStartOf;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_constraintGuide_begin = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_constraintGuide_begin;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_constraintGuide_end = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_constraintGuide_end;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_constraintGuide_percent = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_constraintGuide_percent;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_constraintHeight_default = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_constraintHeight_default;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_constraintHeight_max = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_constraintHeight_max;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_constraintHeight_min = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_constraintHeight_min;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_constraintHeight_percent = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_constraintHeight_percent;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_constraintHorizontal_bias = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_constraintHorizontal_bias;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_constraintHorizontal_chainStyle = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_constraintHorizontal_chainStyle;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_constraintHorizontal_weight = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_constraintHorizontal_weight;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_constraintLeft_creator = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_constraintLeft_creator;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_constraintLeft_toLeftOf = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_constraintLeft_toLeftOf;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_constraintLeft_toRightOf = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_constraintLeft_toRightOf;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_constraintRight_creator = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_constraintRight_creator;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_constraintRight_toLeftOf = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_constraintRight_toLeftOf;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_constraintRight_toRightOf = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_constraintRight_toRightOf;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_constraintStart_toEndOf = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_constraintStart_toEndOf;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_constraintStart_toStartOf = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_constraintStart_toStartOf;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_constraintTop_creator = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_constraintTop_creator;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_constraintTop_toBottomOf = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_constraintTop_toBottomOf;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_constraintTop_toTopOf = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_constraintTop_toTopOf;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_constraintVertical_bias = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_constraintVertical_bias;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_constraintVertical_chainStyle = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_constraintVertical_chainStyle;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_constraintVertical_weight = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_constraintVertical_weight;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_constraintWidth_default = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_constraintWidth_default;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_constraintWidth_max = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_constraintWidth_max;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_constraintWidth_min = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_constraintWidth_min;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_constraintWidth_percent = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_constraintWidth_percent;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_editor_absoluteX = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_editor_absoluteX;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_editor_absoluteY = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_editor_absoluteY;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_goneMarginBottom = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_goneMarginBottom;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_goneMarginEnd = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_goneMarginEnd;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_goneMarginLeft = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_goneMarginLeft;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_goneMarginRight = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_goneMarginRight;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_goneMarginStart = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_goneMarginStart;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_goneMarginTop = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_goneMarginTop;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_optimizationLevel = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_optimizationLevel;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Drawable.esri = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Drawable.esri;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Drawable.NextPreviousButton = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Drawable.NextPreviousButton;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Drawable.NextPreviousFill = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Drawable.NextPreviousFill;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Drawable.NextPreviousOutline = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Drawable.NextPreviousOutline;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Drawable.PauseFill = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Drawable.PauseFill;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Drawable.PauseOutline = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Drawable.PauseOutline;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Drawable.PlayPauseButton = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Drawable.PlayPauseButton;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Drawable.Thumb = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Drawable.Thumb;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Drawable.TriangleFill = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Drawable.TriangleFill;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Drawable.TriangleOutline = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Drawable.TriangleOutline;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.barrier = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.barrier;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.bottom = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.bottom;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.chains = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.chains;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.CurrentExtentEndTimeLabel = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.CurrentExtentEndTimeLabel;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.CurrentExtentFill = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.CurrentExtentFill;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.CurrentExtentStartTimeLabel = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.CurrentExtentStartTimeLabel;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.dimensions = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.dimensions;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.direct = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.direct;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.end = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.end;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.FullExtentEndGuide = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.FullExtentEndGuide;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.FullExtentEndTimeLabel = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.FullExtentEndTimeLabel;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.FullExtentEndTimeTickmark = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.FullExtentEndTimeTickmark;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.FullExtentStartGuide = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.FullExtentStartGuide;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.FullExtentStartTimeLabel = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.FullExtentStartTimeLabel;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.FullExtentStartTimeTickmark = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.FullExtentStartTimeTickmark;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.gone = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.gone;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.invisible = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.invisible;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.left = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.left;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.MaxThumb = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.MaxThumb;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.MaxThumbCenter = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.MaxThumbCenter;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.MinThumb = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.MinThumb;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.MinThumbCenter = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.MinThumbCenter;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.NextButton = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.NextButton;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.NextButtonOutline = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.NextButtonOutline;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.none = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.none;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.packed = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.packed;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.parent = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.parent;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.PauseButtonOutline = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.PauseButtonOutline;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.percent = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.percent;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.PinnedMaxThumb = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.PinnedMaxThumb;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.PinnedMinThumb = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.PinnedMinThumb;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.PlayButtonOutline = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.PlayButtonOutline;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.PlayPauseButton = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.PlayPauseButton;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.PreviousButton = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.PreviousButton;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.PreviousButtonOutline = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.PreviousButtonOutline;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.right = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.right;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.SliderTrack = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.SliderTrack;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.SliderTrackOutline = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.SliderTrackOutline;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.spread = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.spread;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.spread_inside = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.spread_inside;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.standard = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.standard;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.start = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.start;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.ThumbGuideStart = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.ThumbGuideStart;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.Tickmarks = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.Tickmarks;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.top = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.top;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.wrap = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.wrap;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Layout.TimeSlider = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Layout.TimeSlider;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_android_maxHeight = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_android_maxHeight;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_android_maxWidth = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_android_maxWidth;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_android_minHeight = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_android_minHeight;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_android_minWidth = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_android_minWidth;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_android_orientation = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_android_orientation;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_barrierAllowsGoneWidgets = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_barrierAllowsGoneWidgets;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_barrierDirection = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_barrierDirection;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_chainUseRtl = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_chainUseRtl;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_constraintSet = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_constraintSet;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_constraint_referenced_ids = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_constraint_referenced_ids;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_constrainedHeight = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_constrainedHeight;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_constrainedWidth = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_constrainedWidth;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_constraintBaseline_creator = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_constraintBaseline_creator;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_constraintBaseline_toBaselineOf = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_constraintBaseline_toBaselineOf;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_constraintBottom_creator = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_constraintBottom_creator;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_constraintBottom_toBottomOf = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_constraintBottom_toBottomOf;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_constraintBottom_toTopOf = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_constraintBottom_toTopOf;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_constraintCircle = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_constraintCircle;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_constraintCircleAngle = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_constraintCircleAngle;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_constraintCircleRadius = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_constraintCircleRadius;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_constraintDimensionRatio = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_constraintDimensionRatio;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_constraintEnd_toEndOf = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_constraintEnd_toEndOf;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_constraintEnd_toStartOf = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_constraintEnd_toStartOf;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_constraintGuide_begin = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_constraintGuide_begin;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_constraintGuide_end = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_constraintGuide_end;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_constraintGuide_percent = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_constraintGuide_percent;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_constraintHeight_default = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_constraintHeight_default;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_constraintHeight_max = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_constraintHeight_max;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_constraintHeight_min = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_constraintHeight_min;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_constraintHeight_percent = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_constraintHeight_percent;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_constraintHorizontal_bias = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_constraintHorizontal_bias;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_constraintHorizontal_chainStyle = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_constraintHorizontal_chainStyle;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_constraintHorizontal_weight = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_constraintHorizontal_weight;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_constraintLeft_creator = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_constraintLeft_creator;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_constraintLeft_toLeftOf = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_constraintLeft_toLeftOf;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_constraintLeft_toRightOf = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_constraintLeft_toRightOf;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_constraintRight_creator = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_constraintRight_creator;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_constraintRight_toLeftOf = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_constraintRight_toLeftOf;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_constraintRight_toRightOf = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_constraintRight_toRightOf;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_constraintStart_toEndOf = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_constraintStart_toEndOf;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_constraintStart_toStartOf = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_constraintStart_toStartOf;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_constraintTop_creator = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_constraintTop_creator;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_constraintTop_toBottomOf = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_constraintTop_toBottomOf;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_constraintTop_toTopOf = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_constraintTop_toTopOf;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_constraintVertical_bias = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_constraintVertical_bias;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_constraintVertical_chainStyle = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_constraintVertical_chainStyle;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_constraintVertical_weight = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_constraintVertical_weight;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_constraintWidth_default = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_constraintWidth_default;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_constraintWidth_max = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_constraintWidth_max;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_constraintWidth_min = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_constraintWidth_min;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_constraintWidth_percent = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_constraintWidth_percent;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_editor_absoluteX = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_editor_absoluteX;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_editor_absoluteY = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_editor_absoluteY;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_goneMarginBottom = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_goneMarginBottom;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_goneMarginEnd = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_goneMarginEnd;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_goneMarginLeft = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_goneMarginLeft;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_goneMarginRight = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_goneMarginRight;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_goneMarginStart = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_goneMarginStart;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_goneMarginTop = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_goneMarginTop;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_optimizationLevel = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_optimizationLevel;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_placeholder = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_placeholder;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_placeholder_content = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_placeholder_content;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_placeholder_emptyVisibility = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_placeholder_emptyVisibility;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_android_alpha = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_android_alpha;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_android_elevation = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_android_elevation;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_android_id = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_android_id;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_android_layout_height = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_android_layout_height;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_android_layout_marginBottom = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_android_layout_marginBottom;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_android_layout_marginEnd = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_android_layout_marginEnd;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_android_layout_marginLeft = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_android_layout_marginLeft;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_android_layout_marginRight = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_android_layout_marginRight;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_android_layout_marginStart = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_android_layout_marginStart;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_android_layout_marginTop = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_android_layout_marginTop;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_android_layout_width = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_android_layout_width;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_android_orientation = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_android_orientation;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_android_rotation = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_android_rotation;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_android_rotationX = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_android_rotationX;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_android_rotationY = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_android_rotationY;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_android_scaleX = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_android_scaleX;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_android_scaleY = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_android_scaleY;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_android_transformPivotX = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_android_transformPivotX;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_android_transformPivotY = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_android_transformPivotY;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_android_translationX = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_android_translationX;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_android_translationY = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_android_translationY;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_android_translationZ = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_android_translationZ;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_android_visibility = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_android_visibility;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_constrainedHeight = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_constrainedHeight;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_constrainedWidth = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_constrainedWidth;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_constraintBaseline_creator = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_constraintBaseline_creator;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_constraintBaseline_toBaselineOf = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_constraintBaseline_toBaselineOf;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_constraintBottom_creator = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_constraintBottom_creator;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_constraintBottom_toBottomOf = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_constraintBottom_toBottomOf;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_constraintBottom_toTopOf = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_constraintBottom_toTopOf;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_constraintCircle = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_constraintCircle;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_constraintCircleAngle = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_constraintCircleAngle;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_constraintCircleRadius = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_constraintCircleRadius;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_constraintDimensionRatio = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_constraintDimensionRatio;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_constraintEnd_toEndOf = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_constraintEnd_toEndOf;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_constraintEnd_toStartOf = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_constraintEnd_toStartOf;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_constraintGuide_begin = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_constraintGuide_begin;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_constraintGuide_end = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_constraintGuide_end;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_constraintGuide_percent = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_constraintGuide_percent;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_constraintHeight_default = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_constraintHeight_default;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_constraintHeight_max = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_constraintHeight_max;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_constraintHeight_min = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_constraintHeight_min;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_constraintHeight_percent = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_constraintHeight_percent;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_constraintHorizontal_bias = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_constraintHorizontal_bias;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_constraintHorizontal_chainStyle = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_constraintHorizontal_chainStyle;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_constraintHorizontal_weight = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_constraintHorizontal_weight;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_constraintLeft_creator = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_constraintLeft_creator;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_constraintLeft_toLeftOf = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_constraintLeft_toLeftOf;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_constraintLeft_toRightOf = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_constraintLeft_toRightOf;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_constraintRight_creator = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_constraintRight_creator;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_constraintRight_toLeftOf = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_constraintRight_toLeftOf;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_constraintRight_toRightOf = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_constraintRight_toRightOf;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_constraintStart_toEndOf = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_constraintStart_toEndOf;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_constraintStart_toStartOf = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_constraintStart_toStartOf;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_constraintTop_creator = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_constraintTop_creator;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_constraintTop_toBottomOf = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_constraintTop_toBottomOf;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_constraintTop_toTopOf = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_constraintTop_toTopOf;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_constraintVertical_bias = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_constraintVertical_bias;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_constraintVertical_chainStyle = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_constraintVertical_chainStyle;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_constraintVertical_weight = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_constraintVertical_weight;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_constraintWidth_default = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_constraintWidth_default;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_constraintWidth_max = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_constraintWidth_max;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_constraintWidth_min = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_constraintWidth_min;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_constraintWidth_percent = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_constraintWidth_percent;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_editor_absoluteX = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_editor_absoluteX;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_editor_absoluteY = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_editor_absoluteY;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_goneMarginBottom = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_goneMarginBottom;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_goneMarginEnd = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_goneMarginEnd;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_goneMarginLeft = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_goneMarginLeft;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_goneMarginRight = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_goneMarginRight;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_goneMarginStart = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_goneMarginStart;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_goneMarginTop = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_goneMarginTop;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.LinearConstraintLayout = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.LinearConstraintLayout;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.LinearConstraintLayout_android_orientation = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.LinearConstraintLayout_android_orientation;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7F010000
			public const int barrierAllowsGoneWidgets = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int barrierDirection = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int chainUseRtl = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int constraintSet = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int constraint_referenced_ids = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int content = 2130771973;
			
			// aapt resource value: 0x7F010006
			public const int emptyVisibility = 2130771974;
			
			// aapt resource value: 0x7F010007
			public const int layout_constrainedHeight = 2130771975;
			
			// aapt resource value: 0x7F010008
			public const int layout_constrainedWidth = 2130771976;
			
			// aapt resource value: 0x7F010009
			public const int layout_constraintBaseline_creator = 2130771977;
			
			// aapt resource value: 0x7F01000A
			public const int layout_constraintBaseline_toBaselineOf = 2130771978;
			
			// aapt resource value: 0x7F01000B
			public const int layout_constraintBottom_creator = 2130771979;
			
			// aapt resource value: 0x7F01000C
			public const int layout_constraintBottom_toBottomOf = 2130771980;
			
			// aapt resource value: 0x7F01000D
			public const int layout_constraintBottom_toTopOf = 2130771981;
			
			// aapt resource value: 0x7F01000E
			public const int layout_constraintCircle = 2130771982;
			
			// aapt resource value: 0x7F01000F
			public const int layout_constraintCircleAngle = 2130771983;
			
			// aapt resource value: 0x7F010010
			public const int layout_constraintCircleRadius = 2130771984;
			
			// aapt resource value: 0x7F010011
			public const int layout_constraintDimensionRatio = 2130771985;
			
			// aapt resource value: 0x7F010012
			public const int layout_constraintEnd_toEndOf = 2130771986;
			
			// aapt resource value: 0x7F010013
			public const int layout_constraintEnd_toStartOf = 2130771987;
			
			// aapt resource value: 0x7F010014
			public const int layout_constraintGuide_begin = 2130771988;
			
			// aapt resource value: 0x7F010015
			public const int layout_constraintGuide_end = 2130771989;
			
			// aapt resource value: 0x7F010016
			public const int layout_constraintGuide_percent = 2130771990;
			
			// aapt resource value: 0x7F010017
			public const int layout_constraintHeight_default = 2130771991;
			
			// aapt resource value: 0x7F010018
			public const int layout_constraintHeight_max = 2130771992;
			
			// aapt resource value: 0x7F010019
			public const int layout_constraintHeight_min = 2130771993;
			
			// aapt resource value: 0x7F01001A
			public const int layout_constraintHeight_percent = 2130771994;
			
			// aapt resource value: 0x7F01001B
			public const int layout_constraintHorizontal_bias = 2130771995;
			
			// aapt resource value: 0x7F01001C
			public const int layout_constraintHorizontal_chainStyle = 2130771996;
			
			// aapt resource value: 0x7F01001D
			public const int layout_constraintHorizontal_weight = 2130771997;
			
			// aapt resource value: 0x7F01001E
			public const int layout_constraintLeft_creator = 2130771998;
			
			// aapt resource value: 0x7F01001F
			public const int layout_constraintLeft_toLeftOf = 2130771999;
			
			// aapt resource value: 0x7F010020
			public const int layout_constraintLeft_toRightOf = 2130772000;
			
			// aapt resource value: 0x7F010021
			public const int layout_constraintRight_creator = 2130772001;
			
			// aapt resource value: 0x7F010022
			public const int layout_constraintRight_toLeftOf = 2130772002;
			
			// aapt resource value: 0x7F010023
			public const int layout_constraintRight_toRightOf = 2130772003;
			
			// aapt resource value: 0x7F010024
			public const int layout_constraintStart_toEndOf = 2130772004;
			
			// aapt resource value: 0x7F010025
			public const int layout_constraintStart_toStartOf = 2130772005;
			
			// aapt resource value: 0x7F010026
			public const int layout_constraintTop_creator = 2130772006;
			
			// aapt resource value: 0x7F010027
			public const int layout_constraintTop_toBottomOf = 2130772007;
			
			// aapt resource value: 0x7F010028
			public const int layout_constraintTop_toTopOf = 2130772008;
			
			// aapt resource value: 0x7F010029
			public const int layout_constraintVertical_bias = 2130772009;
			
			// aapt resource value: 0x7F01002A
			public const int layout_constraintVertical_chainStyle = 2130772010;
			
			// aapt resource value: 0x7F01002B
			public const int layout_constraintVertical_weight = 2130772011;
			
			// aapt resource value: 0x7F01002C
			public const int layout_constraintWidth_default = 2130772012;
			
			// aapt resource value: 0x7F01002D
			public const int layout_constraintWidth_max = 2130772013;
			
			// aapt resource value: 0x7F01002E
			public const int layout_constraintWidth_min = 2130772014;
			
			// aapt resource value: 0x7F01002F
			public const int layout_constraintWidth_percent = 2130772015;
			
			// aapt resource value: 0x7F010030
			public const int layout_editor_absoluteX = 2130772016;
			
			// aapt resource value: 0x7F010031
			public const int layout_editor_absoluteY = 2130772017;
			
			// aapt resource value: 0x7F010032
			public const int layout_goneMarginBottom = 2130772018;
			
			// aapt resource value: 0x7F010033
			public const int layout_goneMarginEnd = 2130772019;
			
			// aapt resource value: 0x7F010034
			public const int layout_goneMarginLeft = 2130772020;
			
			// aapt resource value: 0x7F010035
			public const int layout_goneMarginRight = 2130772021;
			
			// aapt resource value: 0x7F010036
			public const int layout_goneMarginStart = 2130772022;
			
			// aapt resource value: 0x7F010037
			public const int layout_goneMarginTop = 2130772023;
			
			// aapt resource value: 0x7F010038
			public const int layout_optimizationLevel = 2130772024;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020000
			public const int esri = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int NextPreviousButton = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int NextPreviousFill = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int NextPreviousOutline = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int PauseFill = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int PauseOutline = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int PlayPauseButton = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int Thumb = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int TriangleFill = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int TriangleOutline = 2130837513;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F03001A
			public const int angleSlider = 2130903066;
			
			// aapt resource value: 0x7F03001B
			public const int barrier = 2130903067;
			
			// aapt resource value: 0x7F03001C
			public const int bottom = 2130903068;
			
			// aapt resource value: 0x7F03001D
			public const int chains = 2130903069;
			
			// aapt resource value: 0x7F03001E
			public const int checkboxVisibleRangeOnly = 2130903070;
			
			// aapt resource value: 0x7F03001F
			public const int compass = 2130903071;
			
			// aapt resource value: 0x7F030000
			public const int CurrentExtentEndTimeLabel = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int CurrentExtentFill = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int CurrentExtentStartTimeLabel = 2130903042;
			
			// aapt resource value: 0x7F030020
			public const int dimensions = 2130903072;
			
			// aapt resource value: 0x7F030021
			public const int direct = 2130903073;
			
			// aapt resource value: 0x7F030022
			public const int end = 2130903074;
			
			// aapt resource value: 0x7F030003
			public const int FullExtentEndGuide = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int FullExtentEndTimeLabel = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int FullExtentEndTimeTickmark = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int FullExtentStartGuide = 2130903046;
			
			// aapt resource value: 0x7F030007
			public const int FullExtentStartTimeLabel = 2130903047;
			
			// aapt resource value: 0x7F030008
			public const int FullExtentStartTimeTickmark = 2130903048;
			
			// aapt resource value: 0x7F030023
			public const int gone = 2130903075;
			
			// aapt resource value: 0x7F030024
			public const int invisible = 2130903076;
			
			// aapt resource value: 0x7F030025
			public const int layerLegend = 2130903077;
			
			// aapt resource value: 0x7F030026
			public const int left = 2130903078;
			
			// aapt resource value: 0x7F030027
			public const int legend = 2130903079;
			
			// aapt resource value: 0x7F030028
			public const int mapView = 2130903080;
			
			// aapt resource value: 0x7F030009
			public const int MaxThumb = 2130903049;
			
			// aapt resource value: 0x7F03000A
			public const int MaxThumbCenter = 2130903050;
			
			// aapt resource value: 0x7F03000B
			public const int MinThumb = 2130903051;
			
			// aapt resource value: 0x7F03000C
			public const int MinThumbCenter = 2130903052;
			
			// aapt resource value: 0x7F03000D
			public const int NextButton = 2130903053;
			
			// aapt resource value: 0x7F03000E
			public const int NextButtonOutline = 2130903054;
			
			// aapt resource value: 0x7F030029
			public const int none = 2130903081;
			
			// aapt resource value: 0x7F03002A
			public const int packed = 2130903082;
			
			// aapt resource value: 0x7F03002B
			public const int parent = 2130903083;
			
			// aapt resource value: 0x7F03000F
			public const int PauseButtonOutline = 2130903055;
			
			// aapt resource value: 0x7F03002C
			public const int percent = 2130903084;
			
			// aapt resource value: 0x7F030010
			public const int PinnedMaxThumb = 2130903056;
			
			// aapt resource value: 0x7F030011
			public const int PinnedMinThumb = 2130903057;
			
			// aapt resource value: 0x7F030012
			public const int PlayButtonOutline = 2130903058;
			
			// aapt resource value: 0x7F030013
			public const int PlayPauseButton = 2130903059;
			
			// aapt resource value: 0x7F03002D
			public const int popupViewer = 2130903085;
			
			// aapt resource value: 0x7F030014
			public const int PreviousButton = 2130903060;
			
			// aapt resource value: 0x7F030015
			public const int PreviousButtonOutline = 2130903061;
			
			// aapt resource value: 0x7F03002E
			public const int right = 2130903086;
			
			// aapt resource value: 0x7F03002F
			public const int scaleLine = 2130903087;
			
			// aapt resource value: 0x7F030030
			public const int sceneView = 2130903088;
			
			// aapt resource value: 0x7F030031
			public const int sizeSlider = 2130903089;
			
			// aapt resource value: 0x7F030016
			public const int SliderTrack = 2130903062;
			
			// aapt resource value: 0x7F030017
			public const int SliderTrackOutline = 2130903063;
			
			// aapt resource value: 0x7F030032
			public const int spread = 2130903090;
			
			// aapt resource value: 0x7F030033
			public const int spread_inside = 2130903091;
			
			// aapt resource value: 0x7F030034
			public const int standard = 2130903092;
			
			// aapt resource value: 0x7F030035
			public const int start = 2130903093;
			
			// aapt resource value: 0x7F030036
			public const int styleSelector = 2130903094;
			
			// aapt resource value: 0x7F030037
			public const int symbolDisplay = 2130903095;
			
			// aapt resource value: 0x7F030018
			public const int ThumbGuideStart = 2130903064;
			
			// aapt resource value: 0x7F030019
			public const int Tickmarks = 2130903065;
			
			// aapt resource value: 0x7F030038
			public const int top = 2130903096;
			
			// aapt resource value: 0x7F030039
			public const int wrap = 2130903097;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F040000
			public const int CompassMapViewSample = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int CompassSceneViewSample = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int LayerLegendSample = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int LegendSample = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int Main = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int PopupViewerSample = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int ScaleLineSample = 2130968582;
			
			// aapt resource value: 0x7F040007
			public const int SymbolEditorSample = 2130968583;
			
			// aapt resource value: 0x7F040008
			public const int TimeSlider = 2130968584;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F050000
			public const int app_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			// aapt resource value: { 0x10100C4,0x101011F,0x1010120,0x101013F,0x1010140,0x7F010000,0x7F010001,0x7F010002,0x7F010003,0x7F010004,0x7F010007,0x7F010008,0x7F010009,0x7F01000A,0x7F01000B,0x7F01000C,0x7F01000D,0x7F01000E,0x7F01000F,0x7F010010,0x7F010011,0x7F010012,0x7F010013,0x7F010014,0x7F010015,0x7F010016,0x7F010017,0x7F010018,0x7F010019,0x7F01001A,0x7F01001B,0x7F01001C,0x7F01001D,0x7F01001E,0x7F01001F,0x7F010020,0x7F010021,0x7F010022,0x7F010023,0x7F010024,0x7F010025,0x7F010026,0x7F010027,0x7F010028,0x7F010029,0x7F01002A,0x7F01002B,0x7F01002C,0x7F01002D,0x7F01002E,0x7F01002F,0x7F010030,0x7F010031,0x7F010032,0x7F010033,0x7F010034,0x7F010035,0x7F010036,0x7F010037,0x7F010038 }
			public static int[] ConstraintLayout_Layout = new int[] {
					16842948,
					16843039,
					16843040,
					16843071,
					16843072,
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993,
					2130771994,
					2130771995,
					2130771996,
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772001,
					2130772002,
					2130772003,
					2130772004,
					2130772005,
					2130772006,
					2130772007,
					2130772008,
					2130772009,
					2130772010,
					2130772011,
					2130772012,
					2130772013,
					2130772014,
					2130772015,
					2130772016,
					2130772017,
					2130772018,
					2130772019,
					2130772020,
					2130772021,
					2130772022,
					2130772023,
					2130772024};
			
			// aapt resource value: 2
			public const int ConstraintLayout_Layout_android_maxHeight = 2;
			
			// aapt resource value: 1
			public const int ConstraintLayout_Layout_android_maxWidth = 1;
			
			// aapt resource value: 4
			public const int ConstraintLayout_Layout_android_minHeight = 4;
			
			// aapt resource value: 3
			public const int ConstraintLayout_Layout_android_minWidth = 3;
			
			// aapt resource value: 0
			public const int ConstraintLayout_Layout_android_orientation = 0;
			
			// aapt resource value: 5
			public const int ConstraintLayout_Layout_barrierAllowsGoneWidgets = 5;
			
			// aapt resource value: 6
			public const int ConstraintLayout_Layout_barrierDirection = 6;
			
			// aapt resource value: 7
			public const int ConstraintLayout_Layout_chainUseRtl = 7;
			
			// aapt resource value: 8
			public const int ConstraintLayout_Layout_constraintSet = 8;
			
			// aapt resource value: 9
			public const int ConstraintLayout_Layout_constraint_referenced_ids = 9;
			
			// aapt resource value: 10
			public const int ConstraintLayout_Layout_layout_constrainedHeight = 10;
			
			// aapt resource value: 11
			public const int ConstraintLayout_Layout_layout_constrainedWidth = 11;
			
			// aapt resource value: 12
			public const int ConstraintLayout_Layout_layout_constraintBaseline_creator = 12;
			
			// aapt resource value: 13
			public const int ConstraintLayout_Layout_layout_constraintBaseline_toBaselineOf = 13;
			
			// aapt resource value: 14
			public const int ConstraintLayout_Layout_layout_constraintBottom_creator = 14;
			
			// aapt resource value: 15
			public const int ConstraintLayout_Layout_layout_constraintBottom_toBottomOf = 15;
			
			// aapt resource value: 16
			public const int ConstraintLayout_Layout_layout_constraintBottom_toTopOf = 16;
			
			// aapt resource value: 17
			public const int ConstraintLayout_Layout_layout_constraintCircle = 17;
			
			// aapt resource value: 18
			public const int ConstraintLayout_Layout_layout_constraintCircleAngle = 18;
			
			// aapt resource value: 19
			public const int ConstraintLayout_Layout_layout_constraintCircleRadius = 19;
			
			// aapt resource value: 20
			public const int ConstraintLayout_Layout_layout_constraintDimensionRatio = 20;
			
			// aapt resource value: 21
			public const int ConstraintLayout_Layout_layout_constraintEnd_toEndOf = 21;
			
			// aapt resource value: 22
			public const int ConstraintLayout_Layout_layout_constraintEnd_toStartOf = 22;
			
			// aapt resource value: 23
			public const int ConstraintLayout_Layout_layout_constraintGuide_begin = 23;
			
			// aapt resource value: 24
			public const int ConstraintLayout_Layout_layout_constraintGuide_end = 24;
			
			// aapt resource value: 25
			public const int ConstraintLayout_Layout_layout_constraintGuide_percent = 25;
			
			// aapt resource value: 26
			public const int ConstraintLayout_Layout_layout_constraintHeight_default = 26;
			
			// aapt resource value: 27
			public const int ConstraintLayout_Layout_layout_constraintHeight_max = 27;
			
			// aapt resource value: 28
			public const int ConstraintLayout_Layout_layout_constraintHeight_min = 28;
			
			// aapt resource value: 29
			public const int ConstraintLayout_Layout_layout_constraintHeight_percent = 29;
			
			// aapt resource value: 30
			public const int ConstraintLayout_Layout_layout_constraintHorizontal_bias = 30;
			
			// aapt resource value: 31
			public const int ConstraintLayout_Layout_layout_constraintHorizontal_chainStyle = 31;
			
			// aapt resource value: 32
			public const int ConstraintLayout_Layout_layout_constraintHorizontal_weight = 32;
			
			// aapt resource value: 33
			public const int ConstraintLayout_Layout_layout_constraintLeft_creator = 33;
			
			// aapt resource value: 34
			public const int ConstraintLayout_Layout_layout_constraintLeft_toLeftOf = 34;
			
			// aapt resource value: 35
			public const int ConstraintLayout_Layout_layout_constraintLeft_toRightOf = 35;
			
			// aapt resource value: 36
			public const int ConstraintLayout_Layout_layout_constraintRight_creator = 36;
			
			// aapt resource value: 37
			public const int ConstraintLayout_Layout_layout_constraintRight_toLeftOf = 37;
			
			// aapt resource value: 38
			public const int ConstraintLayout_Layout_layout_constraintRight_toRightOf = 38;
			
			// aapt resource value: 39
			public const int ConstraintLayout_Layout_layout_constraintStart_toEndOf = 39;
			
			// aapt resource value: 40
			public const int ConstraintLayout_Layout_layout_constraintStart_toStartOf = 40;
			
			// aapt resource value: 41
			public const int ConstraintLayout_Layout_layout_constraintTop_creator = 41;
			
			// aapt resource value: 42
			public const int ConstraintLayout_Layout_layout_constraintTop_toBottomOf = 42;
			
			// aapt resource value: 43
			public const int ConstraintLayout_Layout_layout_constraintTop_toTopOf = 43;
			
			// aapt resource value: 44
			public const int ConstraintLayout_Layout_layout_constraintVertical_bias = 44;
			
			// aapt resource value: 45
			public const int ConstraintLayout_Layout_layout_constraintVertical_chainStyle = 45;
			
			// aapt resource value: 46
			public const int ConstraintLayout_Layout_layout_constraintVertical_weight = 46;
			
			// aapt resource value: 47
			public const int ConstraintLayout_Layout_layout_constraintWidth_default = 47;
			
			// aapt resource value: 48
			public const int ConstraintLayout_Layout_layout_constraintWidth_max = 48;
			
			// aapt resource value: 49
			public const int ConstraintLayout_Layout_layout_constraintWidth_min = 49;
			
			// aapt resource value: 50
			public const int ConstraintLayout_Layout_layout_constraintWidth_percent = 50;
			
			// aapt resource value: 51
			public const int ConstraintLayout_Layout_layout_editor_absoluteX = 51;
			
			// aapt resource value: 52
			public const int ConstraintLayout_Layout_layout_editor_absoluteY = 52;
			
			// aapt resource value: 53
			public const int ConstraintLayout_Layout_layout_goneMarginBottom = 53;
			
			// aapt resource value: 54
			public const int ConstraintLayout_Layout_layout_goneMarginEnd = 54;
			
			// aapt resource value: 55
			public const int ConstraintLayout_Layout_layout_goneMarginLeft = 55;
			
			// aapt resource value: 56
			public const int ConstraintLayout_Layout_layout_goneMarginRight = 56;
			
			// aapt resource value: 57
			public const int ConstraintLayout_Layout_layout_goneMarginStart = 57;
			
			// aapt resource value: 58
			public const int ConstraintLayout_Layout_layout_goneMarginTop = 58;
			
			// aapt resource value: 59
			public const int ConstraintLayout_Layout_layout_optimizationLevel = 59;
			
			// aapt resource value: { 0x7F010005,0x7F010006 }
			public static int[] ConstraintLayout_placeholder = new int[] {
					2130771973,
					2130771974};
			
			// aapt resource value: 0
			public const int ConstraintLayout_placeholder_content = 0;
			
			// aapt resource value: 1
			public const int ConstraintLayout_placeholder_emptyVisibility = 1;
			
			// aapt resource value: { 0x10100C4,0x10100D0,0x10100DC,0x10100F4,0x10100F5,0x10100F7,0x10100F8,0x10100F9,0x10100FA,0x101031F,0x1010320,0x1010321,0x1010322,0x1010323,0x1010324,0x1010325,0x1010326,0x1010327,0x1010328,0x10103B5,0x10103B6,0x10103FA,0x1010440,0x7F010007,0x7F010008,0x7F010009,0x7F01000A,0x7F01000B,0x7F01000C,0x7F01000D,0x7F01000E,0x7F01000F,0x7F010010,0x7F010011,0x7F010012,0x7F010013,0x7F010014,0x7F010015,0x7F010016,0x7F010017,0x7F010018,0x7F010019,0x7F01001A,0x7F01001B,0x7F01001C,0x7F01001D,0x7F01001E,0x7F01001F,0x7F010020,0x7F010021,0x7F010022,0x7F010023,0x7F010024,0x7F010025,0x7F010026,0x7F010027,0x7F010028,0x7F010029,0x7F01002A,0x7F01002B,0x7F01002C,0x7F01002D,0x7F01002E,0x7F01002F,0x7F010030,0x7F010031,0x7F010032,0x7F010033,0x7F010034,0x7F010035,0x7F010036,0x7F010037 }
			public static int[] ConstraintSet = new int[] {
					16842948,
					16842960,
					16842972,
					16842996,
					16842997,
					16842999,
					16843000,
					16843001,
					16843002,
					16843551,
					16843552,
					16843553,
					16843554,
					16843555,
					16843556,
					16843557,
					16843558,
					16843559,
					16843560,
					16843701,
					16843702,
					16843770,
					16843840,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993,
					2130771994,
					2130771995,
					2130771996,
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772001,
					2130772002,
					2130772003,
					2130772004,
					2130772005,
					2130772006,
					2130772007,
					2130772008,
					2130772009,
					2130772010,
					2130772011,
					2130772012,
					2130772013,
					2130772014,
					2130772015,
					2130772016,
					2130772017,
					2130772018,
					2130772019,
					2130772020,
					2130772021,
					2130772022,
					2130772023};
			
			// aapt resource value: 9
			public const int ConstraintSet_android_alpha = 9;
			
			// aapt resource value: 22
			public const int ConstraintSet_android_elevation = 22;
			
			// aapt resource value: 1
			public const int ConstraintSet_android_id = 1;
			
			// aapt resource value: 4
			public const int ConstraintSet_android_layout_height = 4;
			
			// aapt resource value: 8
			public const int ConstraintSet_android_layout_marginBottom = 8;
			
			// aapt resource value: 20
			public const int ConstraintSet_android_layout_marginEnd = 20;
			
			// aapt resource value: 5
			public const int ConstraintSet_android_layout_marginLeft = 5;
			
			// aapt resource value: 7
			public const int ConstraintSet_android_layout_marginRight = 7;
			
			// aapt resource value: 19
			public const int ConstraintSet_android_layout_marginStart = 19;
			
			// aapt resource value: 6
			public const int ConstraintSet_android_layout_marginTop = 6;
			
			// aapt resource value: 3
			public const int ConstraintSet_android_layout_width = 3;
			
			// aapt resource value: 0
			public const int ConstraintSet_android_orientation = 0;
			
			// aapt resource value: 16
			public const int ConstraintSet_android_rotation = 16;
			
			// aapt resource value: 17
			public const int ConstraintSet_android_rotationX = 17;
			
			// aapt resource value: 18
			public const int ConstraintSet_android_rotationY = 18;
			
			// aapt resource value: 14
			public const int ConstraintSet_android_scaleX = 14;
			
			// aapt resource value: 15
			public const int ConstraintSet_android_scaleY = 15;
			
			// aapt resource value: 10
			public const int ConstraintSet_android_transformPivotX = 10;
			
			// aapt resource value: 11
			public const int ConstraintSet_android_transformPivotY = 11;
			
			// aapt resource value: 12
			public const int ConstraintSet_android_translationX = 12;
			
			// aapt resource value: 13
			public const int ConstraintSet_android_translationY = 13;
			
			// aapt resource value: 21
			public const int ConstraintSet_android_translationZ = 21;
			
			// aapt resource value: 2
			public const int ConstraintSet_android_visibility = 2;
			
			// aapt resource value: 23
			public const int ConstraintSet_layout_constrainedHeight = 23;
			
			// aapt resource value: 24
			public const int ConstraintSet_layout_constrainedWidth = 24;
			
			// aapt resource value: 25
			public const int ConstraintSet_layout_constraintBaseline_creator = 25;
			
			// aapt resource value: 26
			public const int ConstraintSet_layout_constraintBaseline_toBaselineOf = 26;
			
			// aapt resource value: 27
			public const int ConstraintSet_layout_constraintBottom_creator = 27;
			
			// aapt resource value: 28
			public const int ConstraintSet_layout_constraintBottom_toBottomOf = 28;
			
			// aapt resource value: 29
			public const int ConstraintSet_layout_constraintBottom_toTopOf = 29;
			
			// aapt resource value: 30
			public const int ConstraintSet_layout_constraintCircle = 30;
			
			// aapt resource value: 31
			public const int ConstraintSet_layout_constraintCircleAngle = 31;
			
			// aapt resource value: 32
			public const int ConstraintSet_layout_constraintCircleRadius = 32;
			
			// aapt resource value: 33
			public const int ConstraintSet_layout_constraintDimensionRatio = 33;
			
			// aapt resource value: 34
			public const int ConstraintSet_layout_constraintEnd_toEndOf = 34;
			
			// aapt resource value: 35
			public const int ConstraintSet_layout_constraintEnd_toStartOf = 35;
			
			// aapt resource value: 36
			public const int ConstraintSet_layout_constraintGuide_begin = 36;
			
			// aapt resource value: 37
			public const int ConstraintSet_layout_constraintGuide_end = 37;
			
			// aapt resource value: 38
			public const int ConstraintSet_layout_constraintGuide_percent = 38;
			
			// aapt resource value: 39
			public const int ConstraintSet_layout_constraintHeight_default = 39;
			
			// aapt resource value: 40
			public const int ConstraintSet_layout_constraintHeight_max = 40;
			
			// aapt resource value: 41
			public const int ConstraintSet_layout_constraintHeight_min = 41;
			
			// aapt resource value: 42
			public const int ConstraintSet_layout_constraintHeight_percent = 42;
			
			// aapt resource value: 43
			public const int ConstraintSet_layout_constraintHorizontal_bias = 43;
			
			// aapt resource value: 44
			public const int ConstraintSet_layout_constraintHorizontal_chainStyle = 44;
			
			// aapt resource value: 45
			public const int ConstraintSet_layout_constraintHorizontal_weight = 45;
			
			// aapt resource value: 46
			public const int ConstraintSet_layout_constraintLeft_creator = 46;
			
			// aapt resource value: 47
			public const int ConstraintSet_layout_constraintLeft_toLeftOf = 47;
			
			// aapt resource value: 48
			public const int ConstraintSet_layout_constraintLeft_toRightOf = 48;
			
			// aapt resource value: 49
			public const int ConstraintSet_layout_constraintRight_creator = 49;
			
			// aapt resource value: 50
			public const int ConstraintSet_layout_constraintRight_toLeftOf = 50;
			
			// aapt resource value: 51
			public const int ConstraintSet_layout_constraintRight_toRightOf = 51;
			
			// aapt resource value: 52
			public const int ConstraintSet_layout_constraintStart_toEndOf = 52;
			
			// aapt resource value: 53
			public const int ConstraintSet_layout_constraintStart_toStartOf = 53;
			
			// aapt resource value: 54
			public const int ConstraintSet_layout_constraintTop_creator = 54;
			
			// aapt resource value: 55
			public const int ConstraintSet_layout_constraintTop_toBottomOf = 55;
			
			// aapt resource value: 56
			public const int ConstraintSet_layout_constraintTop_toTopOf = 56;
			
			// aapt resource value: 57
			public const int ConstraintSet_layout_constraintVertical_bias = 57;
			
			// aapt resource value: 58
			public const int ConstraintSet_layout_constraintVertical_chainStyle = 58;
			
			// aapt resource value: 59
			public const int ConstraintSet_layout_constraintVertical_weight = 59;
			
			// aapt resource value: 60
			public const int ConstraintSet_layout_constraintWidth_default = 60;
			
			// aapt resource value: 61
			public const int ConstraintSet_layout_constraintWidth_max = 61;
			
			// aapt resource value: 62
			public const int ConstraintSet_layout_constraintWidth_min = 62;
			
			// aapt resource value: 63
			public const int ConstraintSet_layout_constraintWidth_percent = 63;
			
			// aapt resource value: 64
			public const int ConstraintSet_layout_editor_absoluteX = 64;
			
			// aapt resource value: 65
			public const int ConstraintSet_layout_editor_absoluteY = 65;
			
			// aapt resource value: 66
			public const int ConstraintSet_layout_goneMarginBottom = 66;
			
			// aapt resource value: 67
			public const int ConstraintSet_layout_goneMarginEnd = 67;
			
			// aapt resource value: 68
			public const int ConstraintSet_layout_goneMarginLeft = 68;
			
			// aapt resource value: 69
			public const int ConstraintSet_layout_goneMarginRight = 69;
			
			// aapt resource value: 70
			public const int ConstraintSet_layout_goneMarginStart = 70;
			
			// aapt resource value: 71
			public const int ConstraintSet_layout_goneMarginTop = 71;
			
			// aapt resource value: { 0x10100C4 }
			public static int[] LinearConstraintLayout = new int[] {
					16842948};
			
			// aapt resource value: 0
			public const int LinearConstraintLayout_android_orientation = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
