#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Esri.ArcGISRuntime.Toolkit.SampleApp.Resource", IsApplication=true)]

namespace Esri.ArcGISRuntime.Toolkit.SampleApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.barrierAllowsGoneWidgets = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.barrierAllowsGoneWidgets;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.barrierDirection = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.barrierDirection;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.chainUseRtl = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.chainUseRtl;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.constraintSet = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.constraintSet;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.constraint_referenced_ids = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.constraint_referenced_ids;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.content = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.content;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.emptyVisibility = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.emptyVisibility;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_constrainedHeight = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_constrainedHeight;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_constrainedWidth = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_constrainedWidth;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_constraintBaseline_creator = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_constraintBaseline_creator;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_constraintBaseline_toBaselineOf = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_constraintBaseline_toBaselineOf;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_constraintBottom_creator = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_constraintBottom_creator;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_constraintBottom_toBottomOf = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_constraintBottom_toBottomOf;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_constraintBottom_toTopOf = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_constraintBottom_toTopOf;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_constraintCircle = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_constraintCircle;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_constraintCircleAngle = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_constraintCircleAngle;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_constraintCircleRadius = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_constraintCircleRadius;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_constraintDimensionRatio = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_constraintDimensionRatio;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_constraintEnd_toEndOf = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_constraintEnd_toEndOf;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_constraintEnd_toStartOf = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_constraintEnd_toStartOf;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_constraintGuide_begin = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_constraintGuide_begin;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_constraintGuide_end = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_constraintGuide_end;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_constraintGuide_percent = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_constraintGuide_percent;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_constraintHeight_default = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_constraintHeight_default;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_constraintHeight_max = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_constraintHeight_max;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_constraintHeight_min = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_constraintHeight_min;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_constraintHeight_percent = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_constraintHeight_percent;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_constraintHorizontal_bias = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_constraintHorizontal_bias;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_constraintHorizontal_chainStyle = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_constraintHorizontal_chainStyle;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_constraintHorizontal_weight = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_constraintHorizontal_weight;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_constraintLeft_creator = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_constraintLeft_creator;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_constraintLeft_toLeftOf = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_constraintLeft_toLeftOf;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_constraintLeft_toRightOf = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_constraintLeft_toRightOf;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_constraintRight_creator = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_constraintRight_creator;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_constraintRight_toLeftOf = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_constraintRight_toLeftOf;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_constraintRight_toRightOf = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_constraintRight_toRightOf;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_constraintStart_toEndOf = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_constraintStart_toEndOf;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_constraintStart_toStartOf = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_constraintStart_toStartOf;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_constraintTop_creator = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_constraintTop_creator;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_constraintTop_toBottomOf = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_constraintTop_toBottomOf;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_constraintTop_toTopOf = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_constraintTop_toTopOf;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_constraintVertical_bias = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_constraintVertical_bias;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_constraintVertical_chainStyle = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_constraintVertical_chainStyle;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_constraintVertical_weight = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_constraintVertical_weight;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_constraintWidth_default = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_constraintWidth_default;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_constraintWidth_max = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_constraintWidth_max;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_constraintWidth_min = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_constraintWidth_min;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_constraintWidth_percent = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_constraintWidth_percent;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_editor_absoluteX = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_editor_absoluteX;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_editor_absoluteY = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_editor_absoluteY;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_goneMarginBottom = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_goneMarginBottom;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_goneMarginEnd = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_goneMarginEnd;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_goneMarginLeft = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_goneMarginLeft;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_goneMarginRight = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_goneMarginRight;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_goneMarginStart = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_goneMarginStart;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_goneMarginTop = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_goneMarginTop;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Attribute.layout_optimizationLevel = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Attribute.layout_optimizationLevel;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Drawable.esri = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Drawable.esri;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Drawable.NextPreviousButton = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Drawable.NextPreviousButton;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Drawable.NextPreviousFill = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Drawable.NextPreviousFill;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Drawable.NextPreviousOutline = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Drawable.NextPreviousOutline;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Drawable.PauseFill = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Drawable.PauseFill;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Drawable.PauseOutline = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Drawable.PauseOutline;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Drawable.PlayPauseButton = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Drawable.PlayPauseButton;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Drawable.Thumb = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Drawable.Thumb;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Drawable.TriangleFill = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Drawable.TriangleFill;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Drawable.TriangleOutline = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Drawable.TriangleOutline;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.barrier = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.barrier;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.bottom = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.bottom;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.chains = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.chains;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.CurrentExtentEndTimeLabel = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.CurrentExtentEndTimeLabel;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.CurrentExtentFill = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.CurrentExtentFill;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.CurrentExtentStartTimeLabel = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.CurrentExtentStartTimeLabel;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.dimensions = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.dimensions;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.direct = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.direct;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.end = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.end;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.FullExtentEndGuide = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.FullExtentEndGuide;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.FullExtentEndTimeLabel = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.FullExtentEndTimeLabel;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.FullExtentEndTimeTickmark = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.FullExtentEndTimeTickmark;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.FullExtentStartGuide = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.FullExtentStartGuide;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.FullExtentStartTimeLabel = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.FullExtentStartTimeLabel;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.FullExtentStartTimeTickmark = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.FullExtentStartTimeTickmark;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.gone = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.gone;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.invisible = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.invisible;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.left = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.left;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.MaxThumb = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.MaxThumb;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.MaxThumbCenter = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.MaxThumbCenter;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.MinThumb = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.MinThumb;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.MinThumbCenter = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.MinThumbCenter;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.NextButton = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.NextButton;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.NextButtonOutline = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.NextButtonOutline;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.none = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.none;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.packed = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.packed;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.parent = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.parent;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.PauseButtonOutline = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.PauseButtonOutline;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.percent = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.percent;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.PinnedMaxThumb = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.PinnedMaxThumb;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.PinnedMinThumb = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.PinnedMinThumb;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.PlayButtonOutline = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.PlayButtonOutline;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.PlayPauseButton = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.PlayPauseButton;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.PreviousButton = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.PreviousButton;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.PreviousButtonOutline = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.PreviousButtonOutline;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.right = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.right;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.SliderTrack = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.SliderTrack;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.SliderTrackOutline = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.SliderTrackOutline;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.spread = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.spread;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.spread_inside = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.spread_inside;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.standard = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.standard;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.start = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.start;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.ThumbGuideStart = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.ThumbGuideStart;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.Tickmarks = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.Tickmarks;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.top = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.top;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Id.wrap = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Id.wrap;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Layout.TimeSlider = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Layout.TimeSlider;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_android_maxHeight = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_android_maxHeight;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_android_maxWidth = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_android_maxWidth;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_android_minHeight = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_android_minHeight;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_android_minWidth = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_android_minWidth;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_android_orientation = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_android_orientation;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_barrierAllowsGoneWidgets = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_barrierAllowsGoneWidgets;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_barrierDirection = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_barrierDirection;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_chainUseRtl = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_chainUseRtl;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_constraintSet = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_constraintSet;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_constraint_referenced_ids = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_constraint_referenced_ids;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_constrainedHeight = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_constrainedHeight;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_constrainedWidth = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_constrainedWidth;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_constraintBaseline_creator = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_constraintBaseline_creator;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_constraintBaseline_toBaselineOf = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_constraintBaseline_toBaselineOf;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_constraintBottom_creator = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_constraintBottom_creator;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_constraintBottom_toBottomOf = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_constraintBottom_toBottomOf;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_constraintBottom_toTopOf = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_constraintBottom_toTopOf;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_constraintCircle = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_constraintCircle;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_constraintCircleAngle = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_constraintCircleAngle;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_constraintCircleRadius = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_constraintCircleRadius;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_constraintDimensionRatio = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_constraintDimensionRatio;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_constraintEnd_toEndOf = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_constraintEnd_toEndOf;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_constraintEnd_toStartOf = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_constraintEnd_toStartOf;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_constraintGuide_begin = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_constraintGuide_begin;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_constraintGuide_end = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_constraintGuide_end;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_constraintGuide_percent = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_constraintGuide_percent;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_constraintHeight_default = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_constraintHeight_default;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_constraintHeight_max = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_constraintHeight_max;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_constraintHeight_min = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_constraintHeight_min;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_constraintHeight_percent = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_constraintHeight_percent;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_constraintHorizontal_bias = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_constraintHorizontal_bias;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_constraintHorizontal_chainStyle = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_constraintHorizontal_chainStyle;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_constraintHorizontal_weight = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_constraintHorizontal_weight;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_constraintLeft_creator = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_constraintLeft_creator;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_constraintLeft_toLeftOf = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_constraintLeft_toLeftOf;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_constraintLeft_toRightOf = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_constraintLeft_toRightOf;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_constraintRight_creator = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_constraintRight_creator;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_constraintRight_toLeftOf = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_constraintRight_toLeftOf;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_constraintRight_toRightOf = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_constraintRight_toRightOf;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_constraintStart_toEndOf = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_constraintStart_toEndOf;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_constraintStart_toStartOf = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_constraintStart_toStartOf;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_constraintTop_creator = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_constraintTop_creator;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_constraintTop_toBottomOf = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_constraintTop_toBottomOf;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_constraintTop_toTopOf = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_constraintTop_toTopOf;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_constraintVertical_bias = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_constraintVertical_bias;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_constraintVertical_chainStyle = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_constraintVertical_chainStyle;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_constraintVertical_weight = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_constraintVertical_weight;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_constraintWidth_default = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_constraintWidth_default;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_constraintWidth_max = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_constraintWidth_max;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_constraintWidth_min = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_constraintWidth_min;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_constraintWidth_percent = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_constraintWidth_percent;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_editor_absoluteX = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_editor_absoluteX;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_editor_absoluteY = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_editor_absoluteY;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_goneMarginBottom = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_goneMarginBottom;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_goneMarginEnd = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_goneMarginEnd;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_goneMarginLeft = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_goneMarginLeft;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_goneMarginRight = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_goneMarginRight;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_goneMarginStart = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_goneMarginStart;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_goneMarginTop = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_goneMarginTop;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_Layout_layout_optimizationLevel = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_Layout_layout_optimizationLevel;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_placeholder = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_placeholder;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_placeholder_content = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_placeholder_content;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintLayout_placeholder_emptyVisibility = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintLayout_placeholder_emptyVisibility;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_android_alpha = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_android_alpha;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_android_elevation = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_android_elevation;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_android_id = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_android_id;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_android_layout_height = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_android_layout_height;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_android_layout_marginBottom = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_android_layout_marginBottom;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_android_layout_marginEnd = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_android_layout_marginEnd;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_android_layout_marginLeft = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_android_layout_marginLeft;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_android_layout_marginRight = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_android_layout_marginRight;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_android_layout_marginStart = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_android_layout_marginStart;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_android_layout_marginTop = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_android_layout_marginTop;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_android_layout_width = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_android_layout_width;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_android_orientation = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_android_orientation;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_android_rotation = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_android_rotation;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_android_rotationX = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_android_rotationX;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_android_rotationY = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_android_rotationY;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_android_scaleX = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_android_scaleX;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_android_scaleY = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_android_scaleY;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_android_transformPivotX = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_android_transformPivotX;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_android_transformPivotY = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_android_transformPivotY;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_android_translationX = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_android_translationX;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_android_translationY = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_android_translationY;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_android_translationZ = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_android_translationZ;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_android_visibility = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_android_visibility;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_constrainedHeight = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_constrainedHeight;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_constrainedWidth = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_constrainedWidth;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_constraintBaseline_creator = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_constraintBaseline_creator;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_constraintBaseline_toBaselineOf = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_constraintBaseline_toBaselineOf;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_constraintBottom_creator = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_constraintBottom_creator;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_constraintBottom_toBottomOf = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_constraintBottom_toBottomOf;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_constraintBottom_toTopOf = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_constraintBottom_toTopOf;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_constraintCircle = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_constraintCircle;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_constraintCircleAngle = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_constraintCircleAngle;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_constraintCircleRadius = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_constraintCircleRadius;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_constraintDimensionRatio = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_constraintDimensionRatio;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_constraintEnd_toEndOf = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_constraintEnd_toEndOf;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_constraintEnd_toStartOf = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_constraintEnd_toStartOf;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_constraintGuide_begin = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_constraintGuide_begin;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_constraintGuide_end = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_constraintGuide_end;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_constraintGuide_percent = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_constraintGuide_percent;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_constraintHeight_default = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_constraintHeight_default;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_constraintHeight_max = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_constraintHeight_max;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_constraintHeight_min = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_constraintHeight_min;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_constraintHeight_percent = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_constraintHeight_percent;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_constraintHorizontal_bias = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_constraintHorizontal_bias;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_constraintHorizontal_chainStyle = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_constraintHorizontal_chainStyle;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_constraintHorizontal_weight = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_constraintHorizontal_weight;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_constraintLeft_creator = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_constraintLeft_creator;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_constraintLeft_toLeftOf = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_constraintLeft_toLeftOf;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_constraintLeft_toRightOf = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_constraintLeft_toRightOf;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_constraintRight_creator = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_constraintRight_creator;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_constraintRight_toLeftOf = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_constraintRight_toLeftOf;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_constraintRight_toRightOf = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_constraintRight_toRightOf;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_constraintStart_toEndOf = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_constraintStart_toEndOf;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_constraintStart_toStartOf = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_constraintStart_toStartOf;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_constraintTop_creator = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_constraintTop_creator;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_constraintTop_toBottomOf = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_constraintTop_toBottomOf;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_constraintTop_toTopOf = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_constraintTop_toTopOf;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_constraintVertical_bias = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_constraintVertical_bias;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_constraintVertical_chainStyle = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_constraintVertical_chainStyle;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_constraintVertical_weight = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_constraintVertical_weight;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_constraintWidth_default = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_constraintWidth_default;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_constraintWidth_max = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_constraintWidth_max;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_constraintWidth_min = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_constraintWidth_min;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_constraintWidth_percent = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_constraintWidth_percent;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_editor_absoluteX = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_editor_absoluteX;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_editor_absoluteY = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_editor_absoluteY;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_goneMarginBottom = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_goneMarginBottom;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_goneMarginEnd = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_goneMarginEnd;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_goneMarginLeft = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_goneMarginLeft;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_goneMarginRight = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_goneMarginRight;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_goneMarginStart = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_goneMarginStart;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.ConstraintSet_layout_goneMarginTop = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.ConstraintSet_layout_goneMarginTop;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.LinearConstraintLayout = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.LinearConstraintLayout;
			global::Esri.ArcGISRuntime.Toolkit.Resource.Styleable.LinearConstraintLayout_android_orientation = global::Esri.ArcGISRuntime.Toolkit.SampleApp.Resource.Styleable.LinearConstraintLayout_android_orientation;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7F010000
			public const int sports_array = 2130771968;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7F020000
			public const int barrierAllowsGoneWidgets = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int barrierDirection = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int chainUseRtl = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int constraintSet = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int constraint_referenced_ids = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int content = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int emptyVisibility = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int layout_constrainedHeight = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int layout_constrainedWidth = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int layout_constraintBaseline_creator = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int layout_constraintBaseline_toBaselineOf = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int layout_constraintBottom_creator = 2130837515;
			
			// aapt resource value: 0x7F02000C
			public const int layout_constraintBottom_toBottomOf = 2130837516;
			
			// aapt resource value: 0x7F02000D
			public const int layout_constraintBottom_toTopOf = 2130837517;
			
			// aapt resource value: 0x7F02000E
			public const int layout_constraintCircle = 2130837518;
			
			// aapt resource value: 0x7F02000F
			public const int layout_constraintCircleAngle = 2130837519;
			
			// aapt resource value: 0x7F020010
			public const int layout_constraintCircleRadius = 2130837520;
			
			// aapt resource value: 0x7F020011
			public const int layout_constraintDimensionRatio = 2130837521;
			
			// aapt resource value: 0x7F020012
			public const int layout_constraintEnd_toEndOf = 2130837522;
			
			// aapt resource value: 0x7F020013
			public const int layout_constraintEnd_toStartOf = 2130837523;
			
			// aapt resource value: 0x7F020014
			public const int layout_constraintGuide_begin = 2130837524;
			
			// aapt resource value: 0x7F020015
			public const int layout_constraintGuide_end = 2130837525;
			
			// aapt resource value: 0x7F020016
			public const int layout_constraintGuide_percent = 2130837526;
			
			// aapt resource value: 0x7F020017
			public const int layout_constraintHeight_default = 2130837527;
			
			// aapt resource value: 0x7F020018
			public const int layout_constraintHeight_max = 2130837528;
			
			// aapt resource value: 0x7F020019
			public const int layout_constraintHeight_min = 2130837529;
			
			// aapt resource value: 0x7F02001A
			public const int layout_constraintHeight_percent = 2130837530;
			
			// aapt resource value: 0x7F02001B
			public const int layout_constraintHorizontal_bias = 2130837531;
			
			// aapt resource value: 0x7F02001C
			public const int layout_constraintHorizontal_chainStyle = 2130837532;
			
			// aapt resource value: 0x7F02001D
			public const int layout_constraintHorizontal_weight = 2130837533;
			
			// aapt resource value: 0x7F02001E
			public const int layout_constraintLeft_creator = 2130837534;
			
			// aapt resource value: 0x7F02001F
			public const int layout_constraintLeft_toLeftOf = 2130837535;
			
			// aapt resource value: 0x7F020020
			public const int layout_constraintLeft_toRightOf = 2130837536;
			
			// aapt resource value: 0x7F020021
			public const int layout_constraintRight_creator = 2130837537;
			
			// aapt resource value: 0x7F020022
			public const int layout_constraintRight_toLeftOf = 2130837538;
			
			// aapt resource value: 0x7F020023
			public const int layout_constraintRight_toRightOf = 2130837539;
			
			// aapt resource value: 0x7F020024
			public const int layout_constraintStart_toEndOf = 2130837540;
			
			// aapt resource value: 0x7F020025
			public const int layout_constraintStart_toStartOf = 2130837541;
			
			// aapt resource value: 0x7F020026
			public const int layout_constraintTop_creator = 2130837542;
			
			// aapt resource value: 0x7F020027
			public const int layout_constraintTop_toBottomOf = 2130837543;
			
			// aapt resource value: 0x7F020028
			public const int layout_constraintTop_toTopOf = 2130837544;
			
			// aapt resource value: 0x7F020029
			public const int layout_constraintVertical_bias = 2130837545;
			
			// aapt resource value: 0x7F02002A
			public const int layout_constraintVertical_chainStyle = 2130837546;
			
			// aapt resource value: 0x7F02002B
			public const int layout_constraintVertical_weight = 2130837547;
			
			// aapt resource value: 0x7F02002C
			public const int layout_constraintWidth_default = 2130837548;
			
			// aapt resource value: 0x7F02002D
			public const int layout_constraintWidth_max = 2130837549;
			
			// aapt resource value: 0x7F02002E
			public const int layout_constraintWidth_min = 2130837550;
			
			// aapt resource value: 0x7F02002F
			public const int layout_constraintWidth_percent = 2130837551;
			
			// aapt resource value: 0x7F020030
			public const int layout_editor_absoluteX = 2130837552;
			
			// aapt resource value: 0x7F020031
			public const int layout_editor_absoluteY = 2130837553;
			
			// aapt resource value: 0x7F020032
			public const int layout_goneMarginBottom = 2130837554;
			
			// aapt resource value: 0x7F020033
			public const int layout_goneMarginEnd = 2130837555;
			
			// aapt resource value: 0x7F020034
			public const int layout_goneMarginLeft = 2130837556;
			
			// aapt resource value: 0x7F020035
			public const int layout_goneMarginRight = 2130837557;
			
			// aapt resource value: 0x7F020036
			public const int layout_goneMarginStart = 2130837558;
			
			// aapt resource value: 0x7F020037
			public const int layout_goneMarginTop = 2130837559;
			
			// aapt resource value: 0x7F020038
			public const int layout_optimizationLevel = 2130837560;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F030000
			public const int esri = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int NextPreviousButton = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int NextPreviousFill = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int NextPreviousOutline = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int PauseFill = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int PauseOutline = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int PlayPauseButton = 2130903046;
			
			// aapt resource value: 0x7F030007
			public const int Thumb = 2130903047;
			
			// aapt resource value: 0x7F030008
			public const int TriangleFill = 2130903048;
			
			// aapt resource value: 0x7F030009
			public const int TriangleOutline = 2130903049;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F040000
			public const int AddToObservableButton = 2130968576;
			
			// aapt resource value: 0x7F04001C
			public const int angleSlider = 2130968604;
			
			// aapt resource value: 0x7F04001D
			public const int barrier = 2130968605;
			
			// aapt resource value: 0x7F04001E
			public const int bookmarksView = 2130968606;
			
			// aapt resource value: 0x7F04001F
			public const int bottom = 2130968607;
			
			// aapt resource value: 0x7F040020
			public const int chains = 2130968608;
			
			// aapt resource value: 0x7F040021
			public const int checkboxVisibleRangeOnly = 2130968609;
			
			// aapt resource value: 0x7F040022
			public const int compass = 2130968610;
			
			// aapt resource value: 0x7F040001
			public const int CurrentExtentEndTimeLabel = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int CurrentExtentFill = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int CurrentExtentStartTimeLabel = 2130968579;
			
			// aapt resource value: 0x7F040023
			public const int dimensions = 2130968611;
			
			// aapt resource value: 0x7F040024
			public const int direct = 2130968612;
			
			// aapt resource value: 0x7F040025
			public const int end = 2130968613;
			
			// aapt resource value: 0x7F040004
			public const int FullExtentEndGuide = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int FullExtentEndTimeLabel = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int FullExtentEndTimeTickmark = 2130968582;
			
			// aapt resource value: 0x7F040007
			public const int FullExtentStartGuide = 2130968583;
			
			// aapt resource value: 0x7F040008
			public const int FullExtentStartTimeLabel = 2130968584;
			
			// aapt resource value: 0x7F040009
			public const int FullExtentStartTimeTickmark = 2130968585;
			
			// aapt resource value: 0x7F040026
			public const int gone = 2130968614;
			
			// aapt resource value: 0x7F040027
			public const int invisible = 2130968615;
			
			// aapt resource value: 0x7F040028
			public const int layerLegend = 2130968616;
			
			// aapt resource value: 0x7F040029
			public const int left = 2130968617;
			
			// aapt resource value: 0x7F04002A
			public const int legend = 2130968618;
			
			// aapt resource value: 0x7F04002B
			public const int mapView = 2130968619;
			
			// aapt resource value: 0x7F04000A
			public const int MaxThumb = 2130968586;
			
			// aapt resource value: 0x7F04000B
			public const int MaxThumbCenter = 2130968587;
			
			// aapt resource value: 0x7F04000C
			public const int MinThumb = 2130968588;
			
			// aapt resource value: 0x7F04000D
			public const int MinThumbCenter = 2130968589;
			
			// aapt resource value: 0x7F04000E
			public const int NextButton = 2130968590;
			
			// aapt resource value: 0x7F04000F
			public const int NextButtonOutline = 2130968591;
			
			// aapt resource value: 0x7F04002C
			public const int none = 2130968620;
			
			// aapt resource value: 0x7F04002D
			public const int packed = 2130968621;
			
			// aapt resource value: 0x7F04002E
			public const int parent = 2130968622;
			
			// aapt resource value: 0x7F040010
			public const int PauseButtonOutline = 2130968592;
			
			// aapt resource value: 0x7F04002F
			public const int percent = 2130968623;
			
			// aapt resource value: 0x7F040011
			public const int PinnedMaxThumb = 2130968593;
			
			// aapt resource value: 0x7F040012
			public const int PinnedMinThumb = 2130968594;
			
			// aapt resource value: 0x7F040013
			public const int PlayButtonOutline = 2130968595;
			
			// aapt resource value: 0x7F040014
			public const int PlayPauseButton = 2130968596;
			
			// aapt resource value: 0x7F040030
			public const int popupViewer = 2130968624;
			
			// aapt resource value: 0x7F040031
			public const int prefersManualListCheckbox = 2130968625;
			
			// aapt resource value: 0x7F040015
			public const int PreviousButton = 2130968597;
			
			// aapt resource value: 0x7F040016
			public const int PreviousButtonOutline = 2130968598;
			
			// aapt resource value: 0x7F040017
			public const int RemoveFromObservableButton = 2130968599;
			
			// aapt resource value: 0x7F040032
			public const int right = 2130968626;
			
			// aapt resource value: 0x7F040033
			public const int scaleLine = 2130968627;
			
			// aapt resource value: 0x7F040034
			public const int sceneView = 2130968628;
			
			// aapt resource value: 0x7F040035
			public const int setObservableListButton = 2130968629;
			
			// aapt resource value: 0x7F040036
			public const int setStaticListButton = 2130968630;
			
			// aapt resource value: 0x7F040037
			public const int sizeSlider = 2130968631;
			
			// aapt resource value: 0x7F040018
			public const int SliderTrack = 2130968600;
			
			// aapt resource value: 0x7F040019
			public const int SliderTrackOutline = 2130968601;
			
			// aapt resource value: 0x7F040038
			public const int spread = 2130968632;
			
			// aapt resource value: 0x7F040039
			public const int spread_inside = 2130968633;
			
			// aapt resource value: 0x7F04003A
			public const int standard = 2130968634;
			
			// aapt resource value: 0x7F04003B
			public const int start = 2130968635;
			
			// aapt resource value: 0x7F04003C
			public const int styleSelector = 2130968636;
			
			// aapt resource value: 0x7F04003D
			public const int swapMapButton = 2130968637;
			
			// aapt resource value: 0x7F04003E
			public const int symbolDisplay = 2130968638;
			
			// aapt resource value: 0x7F04001A
			public const int ThumbGuideStart = 2130968602;
			
			// aapt resource value: 0x7F04001B
			public const int Tickmarks = 2130968603;
			
			// aapt resource value: 0x7F04003F
			public const int top = 2130968639;
			
			// aapt resource value: 0x7F040040
			public const int wrap = 2130968640;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F050000
			public const int BookmarksSample = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int CompassMapViewSample = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int CompassSceneViewSample = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int LayerLegendSample = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int LegendSample = 2131034116;
			
			// aapt resource value: 0x7F050005
			public const int Main = 2131034117;
			
			// aapt resource value: 0x7F050006
			public const int PopupViewerSample = 2131034118;
			
			// aapt resource value: 0x7F050007
			public const int ScaleLineSample = 2131034119;
			
			// aapt resource value: 0x7F050008
			public const int SymbolEditorSample = 2131034120;
			
			// aapt resource value: 0x7F050009
			public const int TimeSlider = 2131034121;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F060000
			public const int app_name = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			// aapt resource value: { 0x10100C4,0x101011F,0x1010120,0x101013F,0x1010140,0x7F020000,0x7F020001,0x7F020002,0x7F020003,0x7F020004,0x7F020007,0x7F020008,0x7F020009,0x7F02000A,0x7F02000B,0x7F02000C,0x7F02000D,0x7F02000E,0x7F02000F,0x7F020010,0x7F020011,0x7F020012,0x7F020013,0x7F020014,0x7F020015,0x7F020016,0x7F020017,0x7F020018,0x7F020019,0x7F02001A,0x7F02001B,0x7F02001C,0x7F02001D,0x7F02001E,0x7F02001F,0x7F020020,0x7F020021,0x7F020022,0x7F020023,0x7F020024,0x7F020025,0x7F020026,0x7F020027,0x7F020028,0x7F020029,0x7F02002A,0x7F02002B,0x7F02002C,0x7F02002D,0x7F02002E,0x7F02002F,0x7F020030,0x7F020031,0x7F020032,0x7F020033,0x7F020034,0x7F020035,0x7F020036,0x7F020037,0x7F020038 }
			public static int[] ConstraintLayout_Layout = new int[] {
					16842948,
					16843039,
					16843040,
					16843071,
					16843072,
					2130837504,
					2130837505,
					2130837506,
					2130837507,
					2130837508,
					2130837511,
					2130837512,
					2130837513,
					2130837514,
					2130837515,
					2130837516,
					2130837517,
					2130837518,
					2130837519,
					2130837520,
					2130837521,
					2130837522,
					2130837523,
					2130837524,
					2130837525,
					2130837526,
					2130837527,
					2130837528,
					2130837529,
					2130837530,
					2130837531,
					2130837532,
					2130837533,
					2130837534,
					2130837535,
					2130837536,
					2130837537,
					2130837538,
					2130837539,
					2130837540,
					2130837541,
					2130837542,
					2130837543,
					2130837544,
					2130837545,
					2130837546,
					2130837547,
					2130837548,
					2130837549,
					2130837550,
					2130837551,
					2130837552,
					2130837553,
					2130837554,
					2130837555,
					2130837556,
					2130837557,
					2130837558,
					2130837559,
					2130837560};
			
			// aapt resource value: 2
			public const int ConstraintLayout_Layout_android_maxHeight = 2;
			
			// aapt resource value: 1
			public const int ConstraintLayout_Layout_android_maxWidth = 1;
			
			// aapt resource value: 4
			public const int ConstraintLayout_Layout_android_minHeight = 4;
			
			// aapt resource value: 3
			public const int ConstraintLayout_Layout_android_minWidth = 3;
			
			// aapt resource value: 0
			public const int ConstraintLayout_Layout_android_orientation = 0;
			
			// aapt resource value: 5
			public const int ConstraintLayout_Layout_barrierAllowsGoneWidgets = 5;
			
			// aapt resource value: 6
			public const int ConstraintLayout_Layout_barrierDirection = 6;
			
			// aapt resource value: 7
			public const int ConstraintLayout_Layout_chainUseRtl = 7;
			
			// aapt resource value: 8
			public const int ConstraintLayout_Layout_constraintSet = 8;
			
			// aapt resource value: 9
			public const int ConstraintLayout_Layout_constraint_referenced_ids = 9;
			
			// aapt resource value: 10
			public const int ConstraintLayout_Layout_layout_constrainedHeight = 10;
			
			// aapt resource value: 11
			public const int ConstraintLayout_Layout_layout_constrainedWidth = 11;
			
			// aapt resource value: 12
			public const int ConstraintLayout_Layout_layout_constraintBaseline_creator = 12;
			
			// aapt resource value: 13
			public const int ConstraintLayout_Layout_layout_constraintBaseline_toBaselineOf = 13;
			
			// aapt resource value: 14
			public const int ConstraintLayout_Layout_layout_constraintBottom_creator = 14;
			
			// aapt resource value: 15
			public const int ConstraintLayout_Layout_layout_constraintBottom_toBottomOf = 15;
			
			// aapt resource value: 16
			public const int ConstraintLayout_Layout_layout_constraintBottom_toTopOf = 16;
			
			// aapt resource value: 17
			public const int ConstraintLayout_Layout_layout_constraintCircle = 17;
			
			// aapt resource value: 18
			public const int ConstraintLayout_Layout_layout_constraintCircleAngle = 18;
			
			// aapt resource value: 19
			public const int ConstraintLayout_Layout_layout_constraintCircleRadius = 19;
			
			// aapt resource value: 20
			public const int ConstraintLayout_Layout_layout_constraintDimensionRatio = 20;
			
			// aapt resource value: 21
			public const int ConstraintLayout_Layout_layout_constraintEnd_toEndOf = 21;
			
			// aapt resource value: 22
			public const int ConstraintLayout_Layout_layout_constraintEnd_toStartOf = 22;
			
			// aapt resource value: 23
			public const int ConstraintLayout_Layout_layout_constraintGuide_begin = 23;
			
			// aapt resource value: 24
			public const int ConstraintLayout_Layout_layout_constraintGuide_end = 24;
			
			// aapt resource value: 25
			public const int ConstraintLayout_Layout_layout_constraintGuide_percent = 25;
			
			// aapt resource value: 26
			public const int ConstraintLayout_Layout_layout_constraintHeight_default = 26;
			
			// aapt resource value: 27
			public const int ConstraintLayout_Layout_layout_constraintHeight_max = 27;
			
			// aapt resource value: 28
			public const int ConstraintLayout_Layout_layout_constraintHeight_min = 28;
			
			// aapt resource value: 29
			public const int ConstraintLayout_Layout_layout_constraintHeight_percent = 29;
			
			// aapt resource value: 30
			public const int ConstraintLayout_Layout_layout_constraintHorizontal_bias = 30;
			
			// aapt resource value: 31
			public const int ConstraintLayout_Layout_layout_constraintHorizontal_chainStyle = 31;
			
			// aapt resource value: 32
			public const int ConstraintLayout_Layout_layout_constraintHorizontal_weight = 32;
			
			// aapt resource value: 33
			public const int ConstraintLayout_Layout_layout_constraintLeft_creator = 33;
			
			// aapt resource value: 34
			public const int ConstraintLayout_Layout_layout_constraintLeft_toLeftOf = 34;
			
			// aapt resource value: 35
			public const int ConstraintLayout_Layout_layout_constraintLeft_toRightOf = 35;
			
			// aapt resource value: 36
			public const int ConstraintLayout_Layout_layout_constraintRight_creator = 36;
			
			// aapt resource value: 37
			public const int ConstraintLayout_Layout_layout_constraintRight_toLeftOf = 37;
			
			// aapt resource value: 38
			public const int ConstraintLayout_Layout_layout_constraintRight_toRightOf = 38;
			
			// aapt resource value: 39
			public const int ConstraintLayout_Layout_layout_constraintStart_toEndOf = 39;
			
			// aapt resource value: 40
			public const int ConstraintLayout_Layout_layout_constraintStart_toStartOf = 40;
			
			// aapt resource value: 41
			public const int ConstraintLayout_Layout_layout_constraintTop_creator = 41;
			
			// aapt resource value: 42
			public const int ConstraintLayout_Layout_layout_constraintTop_toBottomOf = 42;
			
			// aapt resource value: 43
			public const int ConstraintLayout_Layout_layout_constraintTop_toTopOf = 43;
			
			// aapt resource value: 44
			public const int ConstraintLayout_Layout_layout_constraintVertical_bias = 44;
			
			// aapt resource value: 45
			public const int ConstraintLayout_Layout_layout_constraintVertical_chainStyle = 45;
			
			// aapt resource value: 46
			public const int ConstraintLayout_Layout_layout_constraintVertical_weight = 46;
			
			// aapt resource value: 47
			public const int ConstraintLayout_Layout_layout_constraintWidth_default = 47;
			
			// aapt resource value: 48
			public const int ConstraintLayout_Layout_layout_constraintWidth_max = 48;
			
			// aapt resource value: 49
			public const int ConstraintLayout_Layout_layout_constraintWidth_min = 49;
			
			// aapt resource value: 50
			public const int ConstraintLayout_Layout_layout_constraintWidth_percent = 50;
			
			// aapt resource value: 51
			public const int ConstraintLayout_Layout_layout_editor_absoluteX = 51;
			
			// aapt resource value: 52
			public const int ConstraintLayout_Layout_layout_editor_absoluteY = 52;
			
			// aapt resource value: 53
			public const int ConstraintLayout_Layout_layout_goneMarginBottom = 53;
			
			// aapt resource value: 54
			public const int ConstraintLayout_Layout_layout_goneMarginEnd = 54;
			
			// aapt resource value: 55
			public const int ConstraintLayout_Layout_layout_goneMarginLeft = 55;
			
			// aapt resource value: 56
			public const int ConstraintLayout_Layout_layout_goneMarginRight = 56;
			
			// aapt resource value: 57
			public const int ConstraintLayout_Layout_layout_goneMarginStart = 57;
			
			// aapt resource value: 58
			public const int ConstraintLayout_Layout_layout_goneMarginTop = 58;
			
			// aapt resource value: 59
			public const int ConstraintLayout_Layout_layout_optimizationLevel = 59;
			
			// aapt resource value: { 0x7F020005,0x7F020006 }
			public static int[] ConstraintLayout_placeholder = new int[] {
					2130837509,
					2130837510};
			
			// aapt resource value: 0
			public const int ConstraintLayout_placeholder_content = 0;
			
			// aapt resource value: 1
			public const int ConstraintLayout_placeholder_emptyVisibility = 1;
			
			// aapt resource value: { 0x10100C4,0x10100D0,0x10100DC,0x10100F4,0x10100F5,0x10100F7,0x10100F8,0x10100F9,0x10100FA,0x101031F,0x1010320,0x1010321,0x1010322,0x1010323,0x1010324,0x1010325,0x1010326,0x1010327,0x1010328,0x10103B5,0x10103B6,0x10103FA,0x1010440,0x7F020007,0x7F020008,0x7F020009,0x7F02000A,0x7F02000B,0x7F02000C,0x7F02000D,0x7F02000E,0x7F02000F,0x7F020010,0x7F020011,0x7F020012,0x7F020013,0x7F020014,0x7F020015,0x7F020016,0x7F020017,0x7F020018,0x7F020019,0x7F02001A,0x7F02001B,0x7F02001C,0x7F02001D,0x7F02001E,0x7F02001F,0x7F020020,0x7F020021,0x7F020022,0x7F020023,0x7F020024,0x7F020025,0x7F020026,0x7F020027,0x7F020028,0x7F020029,0x7F02002A,0x7F02002B,0x7F02002C,0x7F02002D,0x7F02002E,0x7F02002F,0x7F020030,0x7F020031,0x7F020032,0x7F020033,0x7F020034,0x7F020035,0x7F020036,0x7F020037 }
			public static int[] ConstraintSet = new int[] {
					16842948,
					16842960,
					16842972,
					16842996,
					16842997,
					16842999,
					16843000,
					16843001,
					16843002,
					16843551,
					16843552,
					16843553,
					16843554,
					16843555,
					16843556,
					16843557,
					16843558,
					16843559,
					16843560,
					16843701,
					16843702,
					16843770,
					16843840,
					2130837511,
					2130837512,
					2130837513,
					2130837514,
					2130837515,
					2130837516,
					2130837517,
					2130837518,
					2130837519,
					2130837520,
					2130837521,
					2130837522,
					2130837523,
					2130837524,
					2130837525,
					2130837526,
					2130837527,
					2130837528,
					2130837529,
					2130837530,
					2130837531,
					2130837532,
					2130837533,
					2130837534,
					2130837535,
					2130837536,
					2130837537,
					2130837538,
					2130837539,
					2130837540,
					2130837541,
					2130837542,
					2130837543,
					2130837544,
					2130837545,
					2130837546,
					2130837547,
					2130837548,
					2130837549,
					2130837550,
					2130837551,
					2130837552,
					2130837553,
					2130837554,
					2130837555,
					2130837556,
					2130837557,
					2130837558,
					2130837559};
			
			// aapt resource value: 9
			public const int ConstraintSet_android_alpha = 9;
			
			// aapt resource value: 22
			public const int ConstraintSet_android_elevation = 22;
			
			// aapt resource value: 1
			public const int ConstraintSet_android_id = 1;
			
			// aapt resource value: 4
			public const int ConstraintSet_android_layout_height = 4;
			
			// aapt resource value: 8
			public const int ConstraintSet_android_layout_marginBottom = 8;
			
			// aapt resource value: 20
			public const int ConstraintSet_android_layout_marginEnd = 20;
			
			// aapt resource value: 5
			public const int ConstraintSet_android_layout_marginLeft = 5;
			
			// aapt resource value: 7
			public const int ConstraintSet_android_layout_marginRight = 7;
			
			// aapt resource value: 19
			public const int ConstraintSet_android_layout_marginStart = 19;
			
			// aapt resource value: 6
			public const int ConstraintSet_android_layout_marginTop = 6;
			
			// aapt resource value: 3
			public const int ConstraintSet_android_layout_width = 3;
			
			// aapt resource value: 0
			public const int ConstraintSet_android_orientation = 0;
			
			// aapt resource value: 16
			public const int ConstraintSet_android_rotation = 16;
			
			// aapt resource value: 17
			public const int ConstraintSet_android_rotationX = 17;
			
			// aapt resource value: 18
			public const int ConstraintSet_android_rotationY = 18;
			
			// aapt resource value: 14
			public const int ConstraintSet_android_scaleX = 14;
			
			// aapt resource value: 15
			public const int ConstraintSet_android_scaleY = 15;
			
			// aapt resource value: 10
			public const int ConstraintSet_android_transformPivotX = 10;
			
			// aapt resource value: 11
			public const int ConstraintSet_android_transformPivotY = 11;
			
			// aapt resource value: 12
			public const int ConstraintSet_android_translationX = 12;
			
			// aapt resource value: 13
			public const int ConstraintSet_android_translationY = 13;
			
			// aapt resource value: 21
			public const int ConstraintSet_android_translationZ = 21;
			
			// aapt resource value: 2
			public const int ConstraintSet_android_visibility = 2;
			
			// aapt resource value: 23
			public const int ConstraintSet_layout_constrainedHeight = 23;
			
			// aapt resource value: 24
			public const int ConstraintSet_layout_constrainedWidth = 24;
			
			// aapt resource value: 25
			public const int ConstraintSet_layout_constraintBaseline_creator = 25;
			
			// aapt resource value: 26
			public const int ConstraintSet_layout_constraintBaseline_toBaselineOf = 26;
			
			// aapt resource value: 27
			public const int ConstraintSet_layout_constraintBottom_creator = 27;
			
			// aapt resource value: 28
			public const int ConstraintSet_layout_constraintBottom_toBottomOf = 28;
			
			// aapt resource value: 29
			public const int ConstraintSet_layout_constraintBottom_toTopOf = 29;
			
			// aapt resource value: 30
			public const int ConstraintSet_layout_constraintCircle = 30;
			
			// aapt resource value: 31
			public const int ConstraintSet_layout_constraintCircleAngle = 31;
			
			// aapt resource value: 32
			public const int ConstraintSet_layout_constraintCircleRadius = 32;
			
			// aapt resource value: 33
			public const int ConstraintSet_layout_constraintDimensionRatio = 33;
			
			// aapt resource value: 34
			public const int ConstraintSet_layout_constraintEnd_toEndOf = 34;
			
			// aapt resource value: 35
			public const int ConstraintSet_layout_constraintEnd_toStartOf = 35;
			
			// aapt resource value: 36
			public const int ConstraintSet_layout_constraintGuide_begin = 36;
			
			// aapt resource value: 37
			public const int ConstraintSet_layout_constraintGuide_end = 37;
			
			// aapt resource value: 38
			public const int ConstraintSet_layout_constraintGuide_percent = 38;
			
			// aapt resource value: 39
			public const int ConstraintSet_layout_constraintHeight_default = 39;
			
			// aapt resource value: 40
			public const int ConstraintSet_layout_constraintHeight_max = 40;
			
			// aapt resource value: 41
			public const int ConstraintSet_layout_constraintHeight_min = 41;
			
			// aapt resource value: 42
			public const int ConstraintSet_layout_constraintHeight_percent = 42;
			
			// aapt resource value: 43
			public const int ConstraintSet_layout_constraintHorizontal_bias = 43;
			
			// aapt resource value: 44
			public const int ConstraintSet_layout_constraintHorizontal_chainStyle = 44;
			
			// aapt resource value: 45
			public const int ConstraintSet_layout_constraintHorizontal_weight = 45;
			
			// aapt resource value: 46
			public const int ConstraintSet_layout_constraintLeft_creator = 46;
			
			// aapt resource value: 47
			public const int ConstraintSet_layout_constraintLeft_toLeftOf = 47;
			
			// aapt resource value: 48
			public const int ConstraintSet_layout_constraintLeft_toRightOf = 48;
			
			// aapt resource value: 49
			public const int ConstraintSet_layout_constraintRight_creator = 49;
			
			// aapt resource value: 50
			public const int ConstraintSet_layout_constraintRight_toLeftOf = 50;
			
			// aapt resource value: 51
			public const int ConstraintSet_layout_constraintRight_toRightOf = 51;
			
			// aapt resource value: 52
			public const int ConstraintSet_layout_constraintStart_toEndOf = 52;
			
			// aapt resource value: 53
			public const int ConstraintSet_layout_constraintStart_toStartOf = 53;
			
			// aapt resource value: 54
			public const int ConstraintSet_layout_constraintTop_creator = 54;
			
			// aapt resource value: 55
			public const int ConstraintSet_layout_constraintTop_toBottomOf = 55;
			
			// aapt resource value: 56
			public const int ConstraintSet_layout_constraintTop_toTopOf = 56;
			
			// aapt resource value: 57
			public const int ConstraintSet_layout_constraintVertical_bias = 57;
			
			// aapt resource value: 58
			public const int ConstraintSet_layout_constraintVertical_chainStyle = 58;
			
			// aapt resource value: 59
			public const int ConstraintSet_layout_constraintVertical_weight = 59;
			
			// aapt resource value: 60
			public const int ConstraintSet_layout_constraintWidth_default = 60;
			
			// aapt resource value: 61
			public const int ConstraintSet_layout_constraintWidth_max = 61;
			
			// aapt resource value: 62
			public const int ConstraintSet_layout_constraintWidth_min = 62;
			
			// aapt resource value: 63
			public const int ConstraintSet_layout_constraintWidth_percent = 63;
			
			// aapt resource value: 64
			public const int ConstraintSet_layout_editor_absoluteX = 64;
			
			// aapt resource value: 65
			public const int ConstraintSet_layout_editor_absoluteY = 65;
			
			// aapt resource value: 66
			public const int ConstraintSet_layout_goneMarginBottom = 66;
			
			// aapt resource value: 67
			public const int ConstraintSet_layout_goneMarginEnd = 67;
			
			// aapt resource value: 68
			public const int ConstraintSet_layout_goneMarginLeft = 68;
			
			// aapt resource value: 69
			public const int ConstraintSet_layout_goneMarginRight = 69;
			
			// aapt resource value: 70
			public const int ConstraintSet_layout_goneMarginStart = 70;
			
			// aapt resource value: 71
			public const int ConstraintSet_layout_goneMarginTop = 71;
			
			// aapt resource value: { 0x10100C4 }
			public static int[] LinearConstraintLayout = new int[] {
					16842948};
			
			// aapt resource value: 0
			public const int LinearConstraintLayout_android_orientation = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
