// /*******************************************************************************
//  * Copyright 2012-2018 Esri
//  *
//  *  Licensed under the Apache License, Version 2.0 (the "License");
//  *  you may not use this file except in compliance with the License.
//  *  You may obtain a copy of the License at
//  *
//  *  http://www.apache.org/licenses/LICENSE-2.0
//  *
//  *   Unless required by applicable law or agreed to in writing, software
//  *   distributed under the License is distributed on an "AS IS" BASIS,
//  *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  *   See the License for the specific language governing permissions and
//  *   limitations under the License.
//  ******************************************************************************/

#if WPF || WINDOWS_XAML
using System;
using System.Collections.Generic;
using System.Numerics;
using System.Text;
using Windows.Win32;
using Windows.Win32.Foundation;
using Windows.Win32.Graphics.Direct3D;
using Windows.Win32.Graphics.Direct3D11;
using Windows.Win32.Graphics.Dxgi.Common;
using Windows.Win32.System.Com;

namespace Esri.ArcGISRuntime.Toolkit.UI.Controls;

// Direct3D 11 core for the 360/panoramic display. Owns the device and all device resources
// (equirectangular sphere mesh, panorama texture, camera constant buffer) and renders the scene into a
// render-target view supplied by the platform present layer (a swap-chain back buffer on WinUI;
// a shared offscreen texture on WPF). Interop is generated by CsWin32.
internal sealed unsafe partial class PanoramicSurface
{
    private const string VertexShaderSource = """
        cbuffer SceneConstants : register(b0)
        {
            float4x4 WorldViewProjection;
        };
        struct VSInput { float3 Position : POSITION; float2 TexCoord : TEXCOORD0; };
        struct VSOutput { float4 Position : SV_POSITION; float2 TexCoord : TEXCOORD0; };
        VSOutput main(VSInput input)
        {
            VSOutput output;
            output.Position = mul(float4(input.Position, 1.0f), WorldViewProjection);
            output.TexCoord = input.TexCoord;
            return output;
        }
        """;

    private const string PixelShaderSource = """
        Texture2D PanoramaTexture : register(t0);
        SamplerState PanoramaSampler : register(s0);
        struct PSInput { float4 Position : SV_POSITION; float2 TexCoord : TEXCOORD0; };
        float4 main(PSInput input) : SV_TARGET
        {
            return PanoramaTexture.Sample(PanoramaSampler, input.TexCoord);
        }
        """;

    // Markers are pre-projected to NDC on the CPU, so the vertex shader is a pass-through.
    private const string MarkerVertexShaderSource = """
        struct VSInput { float2 Position : POSITION; float2 TexCoord : TEXCOORD0; };
        struct VSOutput { float4 Position : SV_POSITION; float2 TexCoord : TEXCOORD0; };
        VSOutput main(VSInput input)
        {
            VSOutput output;
            output.Position = float4(input.Position, 0.0f, 1.0f);
            output.TexCoord = input.TexCoord;
            return output;
        }
        """;

    private const string MarkerPixelShaderSource = """
        Texture2D MarkerTexture : register(t0);
        SamplerState MarkerSampler : register(s0);
        struct PSInput { float4 Position : SV_POSITION; float2 TexCoord : TEXCOORD0; };
        float4 main(PSInput input) : SV_TARGET
        {
            return MarkerTexture.Sample(MarkerSampler, input.TexCoord);
        }
        """;

    private ID3D11Device* _device;
    private ID3D11DeviceContext* _context;
    private ID3D11VertexShader* _vertexShader;
    private ID3D11PixelShader* _pixelShader;
    private ID3D11InputLayout* _inputLayout;
    private ID3D11Buffer* _vertexBuffer;
    private ID3D11Buffer* _indexBuffer;
    private ID3D11Buffer* _constantBuffer;
    private ID3D11Texture2D* _panoramaTexture;
    private ID3D11ShaderResourceView* _panoramaTextureView;
    private ID3D11SamplerState* _samplerState;
    private ID3D11RasterizerState* _rasterizerState;
    private uint _indexCount;
    private float _clearR, _clearG, _clearB, _clearA = 1f;

    // A texture handed in before the device exists (decoded before the surface Loaded) is stashed here
    // and uploaded once Initialize() creates the device, then released.
    // After a device-lost rebuild the panorama is re-supplied by  display via the DeviceRecreated event (see below)
    // rather than retained here, to avoid a large idle CPU copy.
    private byte[]? _pendingBgra;
    private uint _pendingWidth, _pendingHeight;
    private bool _usingWarp;

    // Marker billboard pass: each marker's swatch is a BGRA texture drawn as a screen-aligned,
    // alpha-blended quad at the (u,v) it projects to (CPU-projected with the same camera as the sphere).
    // Drawn after the sphere, on top.
    private ID3D11VertexShader* _markerVertexShader;
    private ID3D11PixelShader* _markerPixelShader;
    private ID3D11InputLayout* _markerInputLayout;
    private ID3D11Buffer* _markerIndexBuffer;
    private ID3D11Buffer* _markerVertexBuffer;
    private uint _markerVertexCapacity;
    private ID3D11BlendState* _markerBlendState;
    private ID3D11SamplerState* _markerSampler;

    private int _markerCount;
    private float[] _markerU = [];
    private float[] _markerV = [];
    private float[] _markerW = [];
    private float[] _markerH = [];
    private nint[] _markerTextures = [];
    private nint[] _markerViews = [];
    private int[] _visibleBase = [];
    private nint[] _visibleViews = [];
    private MarkerSwatch[]? _pendingMarkers;

    private float _yaw;
    private float _pitch;
    private float _fieldOfView = MathF.PI / 2f;

    // True when the D3D11 device fell back to the WARP software rasterizer (e.g. under Remote Desktop).
    // The WPF present layer reads this because a WARP D3D11 texture cannot be shared with a hardware D3D9Ex device.
    internal bool IsUsingWarp => _usingWarp;

    // Camera state (radians). Owned by the platform camera/gesture layer; consumed by the scene constants.
    // The setters raise CameraChanged so the hosting display can recompute the visible footprint (auto-update).
    public float Yaw
    {
        get => _yaw;
        set => SetCamera(ref _yaw, value);
    }

    public float Pitch
    {
        get => _pitch;
        set => SetCamera(ref _pitch, value);
    }

    public float FieldOfView
    {
        get => _fieldOfView;
        set => SetCamera(ref _fieldOfView, value);
    }

    private void SetCamera(ref float field, float value)
    {
        if (field == value)
            return;

        field = value;
        CameraChanged?.Invoke();
    }

    // The viewport spans FieldOfView across ActualHeight DIPs.
    // Compute drag rotation in rad-per-DIP, so the grabbed point tracks the cursor at screen center.
    private float DragRotationScale()
    {
        double heightDip = ActualHeight;
        if (heightDip <= 0)
            return MouseRotationScale; // defensive: dragging is not really reachable before size is known

        return (float)(2.0 * Math.Tan(FieldOfView / 2.0) / heightDip);
    }

    // Raised when the camera (yaw/pitch/field of view) changes, so the hosting display can recompute the visible
    // footprint while auto-update is enabled.
    internal event Action? CameraChanged;

    // Raised when the surface is tapped/clicked, carrying the position in element (DIP) coordinates.
    internal event Action<double, double>? SurfaceTapped;

    // Raised when device creation, the present bridge, or a render fails inside a present layer
    // (outside the load path), so the hosting display can surface it as IOrientedImageDisplay.Error
    // instead of failing silently.
    internal event Action<Exception>? RenderFailed;

    // Raised after the device is rebuilt following a device-lost (RDP/sleep/TDR).
    // The GPU texture and markers are gone, so the hosting display re-supplies them (re-decode + SetTexture + re-resolve markers);
    // the camera is preserved because it lives on this surface and is untouched by the rebuild.
    // Not raised on the initial device creation.
    internal event Action? DeviceRecreated;

    public bool IsDeviceInitialized => _device is not null;

    // True when the device exists but was removed/reset (TDR, driver update, RDP, sleep);
    // polled after each render to trigger a rebuild.
    internal bool IsDeviceRemoved
    {
        get
        {
            if (_device is null)
                return false;

            try
            {
                // CsWin32 made GetDeviceRemovedReason a void overload that throws on the failed
                // removed-reason HRESULT, so "no throw" means it's healthy.
                _device->GetDeviceRemovedReason();
                return false;
            }
            catch
            {
                return true;
            }
        }
    }

    public bool HasTexture => _panoramaTextureView is not null;

    // The device and context are created by Initialize(); the present layer uses them to create
    // its swap chain (WinUI) or shared texture (WPF) on the same device.
    internal ID3D11Device* Device => _device;

    internal ID3D11DeviceContext* Context => _context;

    // Creates the device and all device-independent resources. Safe to call repeatedly (no-op once created).
    public void Initialize()
    {
        if (_device is not null)
            return;

        CreateDeviceResources();
        CreateShaderResources();
        CreateGeometryResources();
        CreateConstantBuffer();
        CreateRasterizerState();
        CreateSamplerState();
        CreateMarkerResources();

        if (_pendingBgra is byte[] pending)
        {
            byte[] bytes = pending;
            uint w = _pendingWidth, h = _pendingHeight;
            _pendingBgra = null;
            UploadTexture(bytes, w, h);
        }
    }

    // Sets (or replaces) the equirectangular panorama texture from a tightly-packed BGRA8 buffer.
    public void SetTexture(ReadOnlySpan<byte> bgra, uint width, uint height)
    {
        if (width == 0 || height == 0 || bgra.Length < (int)(width * height * 4))
            return;

        if (_device is null)
        {
            // Decoded before the surface created its device; stash and upload from Initialize().
            _pendingBgra = bgra.ToArray();
            _pendingWidth = width;
            _pendingHeight = height;
            return;
        }

        UploadTexture(bgra, width, height);
    }

    private void UploadTexture(ReadOnlySpan<byte> bgra, uint width, uint height)
    {
        Release(ref _panoramaTextureView);
        Release(ref _panoramaTexture);
        CreateBgraTexture(bgra, width, height, out _panoramaTexture, out _panoramaTextureView);
    }

    // Creates an immutable BGRA8 shader-resource texture (and default SRV) from a tightly-packed buffer.
    private void CreateBgraTexture(ReadOnlySpan<byte> bgra, uint width, uint height, out ID3D11Texture2D* texture, out ID3D11ShaderResourceView* view)
    {
        D3D11_TEXTURE2D_DESC desc = new()
        {
            Width = width,
            Height = height,
            MipLevels = 1,
            ArraySize = 1,
            Format = DXGI_FORMAT.DXGI_FORMAT_B8G8R8A8_UNORM,
            SampleDesc = new DXGI_SAMPLE_DESC { Count = 1, Quality = 0 },
            Usage = D3D11_USAGE.D3D11_USAGE_DEFAULT,
            BindFlags = D3D11_BIND_FLAG.D3D11_BIND_SHADER_RESOURCE,
        };

        fixed (byte* pixels = bgra)
        {
            D3D11_SUBRESOURCE_DATA initialData = new() { pSysMem = pixels, SysMemPitch = width * 4 };
            ID3D11Texture2D* tex;
            _device->CreateTexture2D(&desc, &initialData, &tex); // CsWin32 friendly overload throws on failure
            texture = tex;
        }

        ID3D11ShaderResourceView* srv;
        _device->CreateShaderResourceView((ID3D11Resource*)texture, (D3D11_SHADER_RESOURCE_VIEW_DESC*)null, &srv);
        view = srv;
    }

    public void ClearTexture()
    {
        _pendingBgra = null;

        // Unbind PS slot 0 (RenderScene binds _panoramaTextureView there) so releasing our pointer frees the texture
        // instead of leaving it resident on the context while the backdrop is blank.
        if (_context is not null)
        {
            ID3D11ShaderResourceView* nullSrv = null;
            _context->PSSetShaderResources(0, 1, &nullSrv);
        }

        Release(ref _panoramaTextureView);
        Release(ref _panoramaTexture);
    }

    // Sets the backdrop clear color (RGBA, 0..1).
    public void SetClearColor(float r, float g, float b, float a)
    {
        _clearR = r;
        _clearG = g;
        _clearB = b;
        _clearA = a;
    }

    // Renders the panorama sphere into the supplied target view sized to (width, height) device pixels.
    public void RenderScene(ID3D11RenderTargetView* target, uint width, uint height)
    {
        if (_context is null || target is null || _vertexShader is null || _pixelShader is null ||
            _inputLayout is null || _vertexBuffer is null || _indexBuffer is null || _constantBuffer is null ||
            _panoramaTextureView is null || _samplerState is null)
            return;

        UpdateSceneConstants(MathF.Max(1f, width) / MathF.Max(1f, height));

        float* clear = stackalloc float[4] { _clearR, _clearG, _clearB, _clearA };
        _context->ClearRenderTargetView(target, clear);

        D3D11_VIEWPORT viewport = new() { TopLeftX = 0, TopLeftY = 0, Width = width, Height = height, MinDepth = 0f, MaxDepth = 1f };
        _context->RSSetViewports(1, &viewport);
        _context->RSSetState(_rasterizerState);
        _context->OMSetRenderTargets(1, &target, null);
        _context->OMSetBlendState((ID3D11BlendState*)null, (float*)null, 0xffffffff); // opaque sphere pass

        uint stride = (uint)sizeof(VertexPositionTexture);
        uint offset = 0;
        ID3D11Buffer* vertexBuffer = _vertexBuffer;
        ID3D11Buffer* constantBuffer = _constantBuffer;
        ID3D11ShaderResourceView* srv = _panoramaTextureView;
        ID3D11SamplerState* sampler = _samplerState;

        _context->IASetInputLayout(_inputLayout);
        _context->IASetVertexBuffers(0, 1, &vertexBuffer, &stride, &offset);
        _context->IASetIndexBuffer(_indexBuffer, DXGI_FORMAT.DXGI_FORMAT_R16_UINT, 0);
        _context->IASetPrimitiveTopology(D3D_PRIMITIVE_TOPOLOGY.D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST);
        _context->VSSetShader(_vertexShader, null, 0);
        _context->VSSetConstantBuffers(0, 1, &constantBuffer);
        _context->PSSetShader(_pixelShader, null, 0);
        _context->PSSetShaderResources(0, 1, &srv);
        _context->PSSetSamplers(0, 1, &sampler);
        _context->DrawIndexed(_indexCount, 0, 0);

        DrawMarkers(width, height);
    }

    // Clears the target to the background color (no sphere/markers). Used to present a blank frame when there is no
    // texture, so clearing the panorama (footprint change / failed load) actually blanks the displayed buffer instead
    // of leaving the previous frame on screen (the render loops otherwise skip drawing when HasTexture is false).
    public void ClearTarget(ID3D11RenderTargetView* target)
    {
        if (_context is null || target is null)
            return;

        float* clear = stackalloc float[4] { _clearR, _clearG, _clearB, _clearA };
        _context->ClearRenderTargetView(target, clear);
    }

    private void CreateDeviceResources()
    {
        ReadOnlySpan<D3D_FEATURE_LEVEL> featureLevels =
        [
            D3D_FEATURE_LEVEL.D3D_FEATURE_LEVEL_11_0,
            D3D_FEATURE_LEVEL.D3D_FEATURE_LEVEL_10_1,
            D3D_FEATURE_LEVEL.D3D_FEATURE_LEVEL_10_0,
        ];

        ID3D11Device* device;
        ID3D11DeviceContext* context;
        const D3D11_CREATE_DEVICE_FLAG flags = D3D11_CREATE_DEVICE_FLAG.D3D11_CREATE_DEVICE_BGRA_SUPPORT;

        // Re-evaluate per creation: a rebuild after hardware returns must not stay latched on WARP from a prior session.
        _usingWarp = false;

        // Try a hardware device; fall back to the WARP software rasterizer when no compatible GPU is available
        // (common under Remote Desktop / headless sessions), so the panorama still renders.
        HRESULT hr = PInvoke.D3D11CreateDevice(null, D3D_DRIVER_TYPE.D3D_DRIVER_TYPE_HARDWARE, default, flags, featureLevels, PInvoke.D3D11_SDK_VERSION, &device, out _, &context);
        if (hr.Failed)
        {
            PInvoke.D3D11CreateDevice(null, D3D_DRIVER_TYPE.D3D_DRIVER_TYPE_WARP, default, flags, featureLevels, PInvoke.D3D11_SDK_VERSION, &device, out _, &context).ThrowOnFailure();
            _usingWarp = true;
        }

        _device = device;
        _context = context;
    }

    private void CreateShaderResources()
    {
        ID3DBlob* vertexBlob = CompileShader(VertexShaderSource, "vs_4_0");
        ID3DBlob* pixelBlob = CompileShader(PixelShaderSource, "ps_4_0");
        try
        {
            ID3D11VertexShader* vertexShader;
            _device->CreateVertexShader(vertexBlob->GetBufferPointer(), vertexBlob->GetBufferSize(), null, &vertexShader);
            _vertexShader = vertexShader;

            ID3D11PixelShader* pixelShader;
            _device->CreatePixelShader(pixelBlob->GetBufferPointer(), pixelBlob->GetBufferSize(), null, &pixelShader);
            _pixelShader = pixelShader;

            byte[] position = Encoding.ASCII.GetBytes("POSITION\0");
            byte[] texCoord = Encoding.ASCII.GetBytes("TEXCOORD\0");
            fixed (byte* positionPtr = position)
            fixed (byte* texCoordPtr = texCoord)
            {
                D3D11_INPUT_ELEMENT_DESC* elements = stackalloc D3D11_INPUT_ELEMENT_DESC[2];
                elements[0] = new D3D11_INPUT_ELEMENT_DESC
                {
                    SemanticName = new PCSTR(positionPtr),
                    Format = DXGI_FORMAT.DXGI_FORMAT_R32G32B32_FLOAT,
                    AlignedByteOffset = 0,
                    InputSlotClass = D3D11_INPUT_CLASSIFICATION.D3D11_INPUT_PER_VERTEX_DATA,
                };
                elements[1] = new D3D11_INPUT_ELEMENT_DESC
                {
                    SemanticName = new PCSTR(texCoordPtr),
                    Format = DXGI_FORMAT.DXGI_FORMAT_R32G32_FLOAT,
                    AlignedByteOffset = 12,
                    InputSlotClass = D3D11_INPUT_CLASSIFICATION.D3D11_INPUT_PER_VERTEX_DATA,
                };

                ID3D11InputLayout* inputLayout;
                _device->CreateInputLayout(elements, 2, vertexBlob->GetBufferPointer(), vertexBlob->GetBufferSize(), &inputLayout);
                _inputLayout = inputLayout;
            }
        }
        finally
        {
            Release(ref pixelBlob);
            Release(ref vertexBlob);
        }
    }

    private void CreateGeometryResources()
    {
        (VertexPositionTexture[] vertices, ushort[] indices) = CreateSphereMesh();
        _indexCount = (uint)indices.Length;

        D3D11_BUFFER_DESC vertexBufferDesc = new()
        {
            ByteWidth = (uint)(vertices.Length * sizeof(VertexPositionTexture)),
            Usage = D3D11_USAGE.D3D11_USAGE_DEFAULT,
            BindFlags = D3D11_BIND_FLAG.D3D11_BIND_VERTEX_BUFFER,
        };
        D3D11_BUFFER_DESC indexBufferDesc = new()
        {
            ByteWidth = (uint)(indices.Length * sizeof(ushort)),
            Usage = D3D11_USAGE.D3D11_USAGE_DEFAULT,
            BindFlags = D3D11_BIND_FLAG.D3D11_BIND_INDEX_BUFFER,
        };

        fixed (VertexPositionTexture* vertexData = vertices)
        {
            D3D11_SUBRESOURCE_DATA data = new() { pSysMem = vertexData };
            ID3D11Buffer* buffer;
            _device->CreateBuffer(&vertexBufferDesc, &data, &buffer);
            _vertexBuffer = buffer;
        }

        fixed (ushort* indexData = indices)
        {
            D3D11_SUBRESOURCE_DATA data = new() { pSysMem = indexData };
            ID3D11Buffer* buffer;
            _device->CreateBuffer(&indexBufferDesc, &data, &buffer);
            _indexBuffer = buffer;
        }
    }

    private void CreateConstantBuffer()
    {
        D3D11_BUFFER_DESC desc = new()
        {
            ByteWidth = (uint)sizeof(Matrix4x4),
            Usage = D3D11_USAGE.D3D11_USAGE_DEFAULT,
            BindFlags = D3D11_BIND_FLAG.D3D11_BIND_CONSTANT_BUFFER,
        };
        ID3D11Buffer* buffer;
        _device->CreateBuffer(&desc, null, &buffer);
        _constantBuffer = buffer;
    }

    private void CreateRasterizerState()
    {
        D3D11_RASTERIZER_DESC desc = new()
        {
            FillMode = D3D11_FILL_MODE.D3D11_FILL_SOLID,
            CullMode = D3D11_CULL_MODE.D3D11_CULL_NONE,
            FrontCounterClockwise = false,
            DepthClipEnable = true,
        };
        ID3D11RasterizerState* state;
        _device->CreateRasterizerState(&desc, &state);
        _rasterizerState = state;
    }

    private void CreateSamplerState()
    {
        D3D11_SAMPLER_DESC desc = new()
        {
            Filter = D3D11_FILTER.D3D11_FILTER_MIN_MAG_MIP_LINEAR,
            AddressU = D3D11_TEXTURE_ADDRESS_MODE.D3D11_TEXTURE_ADDRESS_WRAP,
            AddressV = D3D11_TEXTURE_ADDRESS_MODE.D3D11_TEXTURE_ADDRESS_CLAMP,
            AddressW = D3D11_TEXTURE_ADDRESS_MODE.D3D11_TEXTURE_ADDRESS_CLAMP,
            ComparisonFunc = D3D11_COMPARISON_FUNC.D3D11_COMPARISON_NEVER,
            MinLOD = 0f,
            MaxLOD = float.MaxValue,
            MaxAnisotropy = 1,
        };
        ID3D11SamplerState* state;
        _device->CreateSamplerState(&desc, &state);
        _samplerState = state;
    }

    // Sets the marker swatches to draw over the panorama (replaces any previous set). Each swatch is a tightly-packed
    // BGRA8 buffer placed at a normalized (u,v). Safe to call before the device exists (stashed, built in Initialize).
    internal void SetMarkers(IReadOnlyList<MarkerSwatch> markers)
    {
        if (_device is null)
        {
            _pendingMarkers = new MarkerSwatch[markers.Count];
            for (int i = 0; i < markers.Count; i++)
            {
                _pendingMarkers[i] = markers[i];
            }

            return;
        }

        BuildGpuMarkers(markers);
    }

    private void CreateMarkerResources()
    {
        ID3DBlob* vertexBlob = CompileShader(MarkerVertexShaderSource, "vs_4_0");
        ID3DBlob* pixelBlob = CompileShader(MarkerPixelShaderSource, "ps_4_0");
        try
        {
            ID3D11VertexShader* vertexShader;
            _device->CreateVertexShader(vertexBlob->GetBufferPointer(), vertexBlob->GetBufferSize(), null, &vertexShader);
            _markerVertexShader = vertexShader;

            ID3D11PixelShader* pixelShader;
            _device->CreatePixelShader(pixelBlob->GetBufferPointer(), pixelBlob->GetBufferSize(), null, &pixelShader);
            _markerPixelShader = pixelShader;

            byte[] position = Encoding.ASCII.GetBytes("POSITION\0");
            byte[] texCoord = Encoding.ASCII.GetBytes("TEXCOORD\0");
            fixed (byte* positionPtr = position)
            fixed (byte* texCoordPtr = texCoord)
            {
                D3D11_INPUT_ELEMENT_DESC* elements = stackalloc D3D11_INPUT_ELEMENT_DESC[2];
                elements[0] = new D3D11_INPUT_ELEMENT_DESC
                {
                    SemanticName = new PCSTR(positionPtr),
                    Format = DXGI_FORMAT.DXGI_FORMAT_R32G32_FLOAT,
                    AlignedByteOffset = 0,
                    InputSlotClass = D3D11_INPUT_CLASSIFICATION.D3D11_INPUT_PER_VERTEX_DATA,
                };
                elements[1] = new D3D11_INPUT_ELEMENT_DESC
                {
                    SemanticName = new PCSTR(texCoordPtr),
                    Format = DXGI_FORMAT.DXGI_FORMAT_R32G32_FLOAT,
                    AlignedByteOffset = 8,
                    InputSlotClass = D3D11_INPUT_CLASSIFICATION.D3D11_INPUT_PER_VERTEX_DATA,
                };

                ID3D11InputLayout* inputLayout;
                _device->CreateInputLayout(elements, 2, vertexBlob->GetBufferPointer(), vertexBlob->GetBufferSize(), &inputLayout);
                _markerInputLayout = inputLayout;
            }
        }
        finally
        {
            Release(ref pixelBlob);
            Release(ref vertexBlob);
        }

        ushort[] indices = [0, 1, 2, 2, 1, 3];
        D3D11_BUFFER_DESC indexBufferDesc = new()
        {
            ByteWidth = (uint)(indices.Length * sizeof(ushort)),
            Usage = D3D11_USAGE.D3D11_USAGE_DEFAULT,
            BindFlags = D3D11_BIND_FLAG.D3D11_BIND_INDEX_BUFFER,
        };
        fixed (ushort* indexData = indices)
        {
            D3D11_SUBRESOURCE_DATA data = new() { pSysMem = indexData };
            ID3D11Buffer* buffer;
            _device->CreateBuffer(&indexBufferDesc, &data, &buffer);
            _markerIndexBuffer = buffer;
        }

        // Straight (non-premultiplied) alpha source-over: the swatch buffers from RuntimeImage are not premultiplied.
        D3D11_BLEND_DESC blendDesc = default;
        D3D11_RENDER_TARGET_BLEND_DESC rtBlend = new()
        {
            BlendEnable = true,
            SrcBlend = D3D11_BLEND.D3D11_BLEND_SRC_ALPHA,
            DestBlend = D3D11_BLEND.D3D11_BLEND_INV_SRC_ALPHA,
            BlendOp = D3D11_BLEND_OP.D3D11_BLEND_OP_ADD,
            SrcBlendAlpha = D3D11_BLEND.D3D11_BLEND_ONE,
            DestBlendAlpha = D3D11_BLEND.D3D11_BLEND_INV_SRC_ALPHA,
            BlendOpAlpha = D3D11_BLEND_OP.D3D11_BLEND_OP_ADD,
            RenderTargetWriteMask = (byte)D3D11_COLOR_WRITE_ENABLE.D3D11_COLOR_WRITE_ENABLE_ALL,
        };
        blendDesc.RenderTarget._0 = rtBlend;
        ID3D11BlendState* blendState;
        _device->CreateBlendState(&blendDesc, &blendState);
        _markerBlendState = blendState;

        D3D11_SAMPLER_DESC samplerDesc = new()
        {
            Filter = D3D11_FILTER.D3D11_FILTER_MIN_MAG_MIP_LINEAR,
            AddressU = D3D11_TEXTURE_ADDRESS_MODE.D3D11_TEXTURE_ADDRESS_CLAMP,
            AddressV = D3D11_TEXTURE_ADDRESS_MODE.D3D11_TEXTURE_ADDRESS_CLAMP,
            AddressW = D3D11_TEXTURE_ADDRESS_MODE.D3D11_TEXTURE_ADDRESS_CLAMP,
            ComparisonFunc = D3D11_COMPARISON_FUNC.D3D11_COMPARISON_NEVER,
            MinLOD = 0f,
            MaxLOD = float.MaxValue,
            MaxAnisotropy = 1,
        };
        ID3D11SamplerState* sampler;
        _device->CreateSamplerState(&samplerDesc, &sampler);
        _markerSampler = sampler;

        if (_pendingMarkers is MarkerSwatch[] pending)
        {
            _pendingMarkers = null;
            BuildGpuMarkers(pending);
        }
    }

    private void BuildGpuMarkers(IReadOnlyList<MarkerSwatch> markers)
    {
        ReleaseGpuMarkers();

        int count = markers.Count;
        _markerCount = count;
        if (count == 0)
            return;

        if (_markerU.Length < count)
        {
            _markerU = new float[count];
            _markerV = new float[count];
            _markerW = new float[count];
            _markerH = new float[count];
            _markerTextures = new nint[count];
            _markerViews = new nint[count];
            _visibleBase = new int[count];
            _visibleViews = new nint[count];
        }

        for (int i = 0; i < count; i++)
        {
            MarkerSwatch marker = markers[i];
            CreateBgraTexture(marker.Bgra, (uint)marker.Width, (uint)marker.Height, out ID3D11Texture2D* texture, out ID3D11ShaderResourceView* view);
            _markerU[i] = marker.U;
            _markerV[i] = marker.V;
            _markerW[i] = marker.Width;
            _markerH[i] = marker.Height;
            _markerTextures[i] = (nint)texture;
            _markerViews[i] = (nint)view;
        }

        uint requiredVertices = (uint)count * 4;
        if (_markerVertexBuffer is null || _markerVertexCapacity < requiredVertices)
        {
            Release(ref _markerVertexBuffer);
            D3D11_BUFFER_DESC desc = new()
            {
                ByteWidth = requiredVertices * (uint)sizeof(MarkerVertex),
                Usage = D3D11_USAGE.D3D11_USAGE_DYNAMIC,
                BindFlags = D3D11_BIND_FLAG.D3D11_BIND_VERTEX_BUFFER,
                CPUAccessFlags = D3D11_CPU_ACCESS_FLAG.D3D11_CPU_ACCESS_WRITE,
            };
            ID3D11Buffer* buffer;
            _device->CreateBuffer(&desc, null, &buffer);
            _markerVertexBuffer = buffer;
            _markerVertexCapacity = requiredVertices;
        }
    }

    // Projects each marker to NDC with the current camera, fills the dynamic vertex buffer, and draws the visible ones
    // as alpha-blended textured quads sized to the swatch's pixel dimensions. Markers behind the camera are skipped.
    private void DrawMarkers(uint width, uint height)
    {
        if (_markerCount == 0 || _markerVertexBuffer is null || _markerVertexShader is null || _markerPixelShader is null ||
            _markerInputLayout is null || _markerIndexBuffer is null || _markerBlendState is null || _markerSampler is null)
            return;

        Matrix4x4 world = Matrix4x4.CreateRotationY(Yaw) * Matrix4x4.CreateRotationX(Pitch);
        Matrix4x4 projection = Matrix4x4.CreatePerspectiveFieldOfView(FieldOfView, MathF.Max(1f, width) / MathF.Max(1f, height), 0.1f, 10f);
        Matrix4x4 worldViewProjection = world * projection;

        D3D11_MAPPED_SUBRESOURCE mapped;
        _context->Map((ID3D11Resource*)_markerVertexBuffer, 0, D3D11_MAP.D3D11_MAP_WRITE_DISCARD, 0, &mapped);
        var vertices = (MarkerVertex*)mapped.pData;
        int visible = 0;
        for (int i = 0; i < _markerCount; i++)
        {
            float theta = _markerU[i] * 2f * MathF.PI;
            float phi = _markerV[i] * MathF.PI;
            var direction = new Vector4(MathF.Sin(phi) * MathF.Cos(theta), MathF.Cos(phi), MathF.Sin(phi) * MathF.Sin(theta), 1f);
            Vector4 clip = Vector4.Transform(direction, worldViewProjection);
            if (clip.W <= 0f)
                continue;

            float ndcX = clip.X / clip.W;
            float ndcY = clip.Y / clip.W;
            float halfX = _markerW[i] / width;
            float halfY = _markerH[i] / height;
            int b = visible * 4;
            vertices[b + 0] = new MarkerVertex(new Vector2(ndcX - halfX, ndcY + halfY), new Vector2(0f, 0f));
            vertices[b + 1] = new MarkerVertex(new Vector2(ndcX + halfX, ndcY + halfY), new Vector2(1f, 0f));
            vertices[b + 2] = new MarkerVertex(new Vector2(ndcX - halfX, ndcY - halfY), new Vector2(0f, 1f));
            vertices[b + 3] = new MarkerVertex(new Vector2(ndcX + halfX, ndcY - halfY), new Vector2(1f, 1f));
            _visibleBase[visible] = b;
            _visibleViews[visible] = _markerViews[i];
            visible++;
        }

        _context->Unmap((ID3D11Resource*)_markerVertexBuffer, 0);
        if (visible == 0)
            return;

        uint stride = (uint)sizeof(MarkerVertex);
        uint offset = 0;
        ID3D11Buffer* vertexBuffer = _markerVertexBuffer;
        ID3D11SamplerState* sampler = _markerSampler;
        float* blendFactor = stackalloc float[4] { 1f, 1f, 1f, 1f };

        _context->IASetInputLayout(_markerInputLayout);
        _context->IASetVertexBuffers(0, 1, &vertexBuffer, &stride, &offset);
        _context->IASetIndexBuffer(_markerIndexBuffer, DXGI_FORMAT.DXGI_FORMAT_R16_UINT, 0);
        _context->IASetPrimitiveTopology(D3D_PRIMITIVE_TOPOLOGY.D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST);
        _context->VSSetShader(_markerVertexShader, null, 0);
        _context->PSSetShader(_markerPixelShader, null, 0);
        _context->PSSetSamplers(0, 1, &sampler);
        _context->OMSetBlendState(_markerBlendState, blendFactor, 0xffffffff);

        for (int j = 0; j < visible; j++)
        {
            ID3D11ShaderResourceView* srv = (ID3D11ShaderResourceView*)_visibleViews[j];
            _context->PSSetShaderResources(0, 1, &srv);
            _context->DrawIndexed(6, 0, _visibleBase[j]);
        }

        _context->OMSetBlendState((ID3D11BlendState*)null, (float*)null, 0xffffffff);
    }

    private void ReleaseGpuMarkers()
    {
        for (int i = 0; i < _markerCount; i++)
        {
            nint view = _markerViews[i];
            if (view != 0)
            {
                _ = ((IUnknown*)view)->Release();
                _markerViews[i] = 0;
            }

            nint texture = _markerTextures[i];
            if (texture != 0)
            {
                _ = ((IUnknown*)texture)->Release();
                _markerTextures[i] = 0;
            }
        }

        _markerCount = 0;
    }

    private void ReleaseMarkerResources()
    {
        ReleaseGpuMarkers();
        Release(ref _markerVertexBuffer);
        Release(ref _markerIndexBuffer);
        Release(ref _markerInputLayout);
        Release(ref _markerPixelShader);
        Release(ref _markerVertexShader);
        Release(ref _markerBlendState);
        Release(ref _markerSampler);
        _markerVertexCapacity = 0;
    }

    private void UpdateSceneConstants(float aspectRatio)
    {
        Matrix4x4 world = Matrix4x4.CreateRotationY(Yaw) * Matrix4x4.CreateRotationX(Pitch);
        Matrix4x4 projection = Matrix4x4.CreatePerspectiveFieldOfView(FieldOfView, aspectRatio, 0.1f, 10f);
        Matrix4x4 worldViewProjection = Matrix4x4.Transpose(world * projection);
        _context->UpdateSubresource((ID3D11Resource*)_constantBuffer, 0, (D3D11_BOX*)null, &worldViewProjection, 0, 0);
    }

    private ID3DBlob* CompileShader(string source, string target)
    {
        byte[] sourceBytes = Encoding.UTF8.GetBytes(source);
        byte[] entryPointBytes = Encoding.ASCII.GetBytes("main\0");
        byte[] targetBytes = Encoding.ASCII.GetBytes(target + "\0");

        fixed (byte* sourcePtr = sourceBytes)
        fixed (byte* entryPointPtr = entryPointBytes)
        fixed (byte* targetPtr = targetBytes)
        {
            ID3DBlob* code;
            ID3DBlob* errors;
            HRESULT hr = PInvoke.D3DCompile(
                sourcePtr,
                (nuint)sourceBytes.Length,
                default,
                null,
                null,
                new PCSTR(entryPointPtr),
                new PCSTR(targetPtr),
                0,
                0,
                &code,
                &errors);

            if (hr.Failed)
            {
                string message = "Shader compilation failed.";
                if (errors is not null)
                {
                    message = new string((sbyte*)errors->GetBufferPointer(), 0, (int)errors->GetBufferSize());
                    errors->Release();
                }

                throw new InvalidOperationException(message);
            }

            if (errors is not null)
                errors->Release();

            return code;
        }
    }

    private static (VertexPositionTexture[] Vertices, ushort[] Indices) CreateSphereMesh()
    {
        const int size = 30;
        var vertices = new VertexPositionTexture[((size * 2) + 1) * (size + 1)];
        var indices = new ushort[(size * 2) * size * 6];
        int v = 0;
        for (int i = 0; i <= size; i++)
        {
            float phi = MathF.PI * i / size;
            for (int j = 0; j <= size * 2; j++)
            {
                float theta = 2f * MathF.PI * j / (size * 2);
                float x = MathF.Sin(phi) * MathF.Cos(theta);
                float y = MathF.Cos(phi);
                float z = MathF.Sin(phi) * MathF.Sin(theta);
                vertices[v++] = new VertexPositionTexture(new Vector3(x, y, z), new Vector2(j / (float)(size * 2), phi / MathF.PI));
            }
        }

        int index = 0;
        for (int x = 0; x < size; x++)
        {
            for (int y = 0; y < size * 2; y++)
            {
                ushort v0 = (ushort)((x * ((size * 2) + 1)) + y);
                ushort v1 = (ushort)(((x + 1) * ((size * 2) + 1)) + y);
                ushort v2 = (ushort)((x * ((size * 2) + 1)) + y + 1);
                ushort v3 = (ushort)(((x + 1) * ((size * 2) + 1)) + y + 1);
                indices[index++] = v0;
                indices[index++] = v1;
                indices[index++] = v2;
                indices[index++] = v2;
                indices[index++] = v1;
                indices[index++] = v3;
            }
        }

        return (vertices, indices);
    }

    private static void Release<T>(ref T* p)
        where T : unmanaged
    {
        if (p is not null)
        {
            _ = ((IUnknown*)p)->Release();
            p = null;
        }
    }

    // Releases the device and all device resources. Called by the platform present layer on Unloaded (idempotent).
    internal void ReleaseDeviceResources()
    {
        ReleaseMarkerResources();
        Release(ref _rasterizerState);
        Release(ref _samplerState);
        Release(ref _panoramaTextureView);
        Release(ref _panoramaTexture);
        Release(ref _constantBuffer);
        Release(ref _indexBuffer);
        Release(ref _vertexBuffer);
        Release(ref _inputLayout);
        Release(ref _pixelShader);
        Release(ref _vertexShader);
        Release(ref _context);
        Release(ref _device);
    }

    private readonly record struct VertexPositionTexture(Vector3 Position, Vector2 TextureCoordinate);

    private readonly record struct MarkerVertex(Vector2 Position, Vector2 TexCoord);

    // A resolved marker ready for the GPU: a tightly-packed BGRA8 swatch and the normalized (u,v) it sits at.
    internal readonly record struct MarkerSwatch(float U, float V, byte[] Bgra, int Width, int Height);
}
#endif
