name: CI

on:
  push:
    branches:
    - main
    - release/*
    paths-ignore:
    - 'docs/**'
  pull_request:
    branches:
    - main
    paths-ignore:
    - 'docs/**'

permissions:
  contents: read

env:
  DOTNET_SDK_VERSION: 11.0.100-preview.7.26381.103
  DOTNET_WORKLOAD_VERSION: 11.0.100-preview.7.26410.2

jobs:
  build:

    runs-on: windows-2025-vs2026
    
    steps:
    - name: Clone Toolkit
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_SDK_VERSION }}
    
    - name: Setup Visual Studio Command Prompt
      uses: microsoft/setup-msbuild@v3
    
    - name: "Update windows SDK"
      uses: fbactions/setup-winsdk@v1
      with:
        winsdk-build-version: 19041
        
    - name: Install MAUI Workload
      run: |
        dotnet workload install maui --version $env:DOTNET_WORKLOAD_VERSION
       
    - name: Build
      run: |
        msbuild /restore /t:Build src/Esri.ArcGISRuntime.Toolkit.sln /p:Configuration=Release
#       msbuild /restore /t:Build src/Esri.ArcGISRuntime.ARToolkit.sln /p:Configuration=Release
      
    - name: Upload artfacts
      uses: actions/upload-artifact@v4
      with:
        name: NuGet Packages
        path: Output/NuGet/Release

  publish:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: build
    runs-on: windows-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Download NuGet packages
      uses: actions/download-artifact@v4
      with:
        name: NuGet Packages
        path: Output/NuGet/Release

    - name: Publish to Esri Nuget Repo
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        dotnet nuget push Output\NuGet\Release\*.nupkg --api-key $env:GITHUB_TOKEN --source https://nuget.pkg.github.com/esri/index.json
